var searchData=
[
  ['karma_3a_3aecastcheckedtype_0',['ECastCheckedType',['../namespace_karma_1_1_e_cast_checked_type.html',1,'Karma']]],
  ['karma_5fapi_1',['KARMA_API',['../_core_8h.html#a0362c0681bf67d6dd6b8d2c75866bef4',1,'Core.h']]],
  ['karmaclassobjectmap_2',['KarmaClassObjectMap',['../class_karma_1_1_karma_class_object_map.html',1,'Karma::KarmaClassObjectMap'],['../class_karma_1_1_karma_class_object_map.html#a89847307c2926edfe4a0273bc0596472',1,'Karma::KarmaClassObjectMap::KarmaClassObjectMap()']]],
  ['karmagui_3',['KarmaGui',['../class_karma_1_1_karma_gui.html',1,'Karma']]],
  ['karmagui_2eh_4',['KarmaGui.h',['../_karma_gui_8h.html',1,'']]],
  ['karmagui_5f3dscene_5fto_5f2dtexture_5fdata_5',['KarmaGui_3DScene_To_2DTexture_Data',['../struct_karma_1_1_karma_gui__3_d_scene___to__2_d_texture___data.html',1,'Karma']]],
  ['karmagui_5fimplglfw_5fdata_6',['KarmaGui_ImplGlfw_Data',['../struct_karma_gui___impl_glfw___data.html',1,'']]],
  ['karmagui_5fimplglfw_5fviewportdata_7',['KarmaGui_ImplGlfw_ViewportData',['../struct_karma_1_1_karma_gui___impl_glfw___viewport_data.html',1,'Karma']]],
  ['karmagui_5fimplopengl3_5fcreatedeviceobjects_8',['KarmaGui_ImplOpenGL3_CreateDeviceObjects',['../class_karma_1_1_karma_gui_open_g_l_handler.html#a3f307062b620e2af795e39b3fc37f486',1,'Karma::KarmaGuiOpenGLHandler']]],
  ['karmagui_5fimplopengl3_5fcreatefontstexture_9',['KarmaGui_ImplOpenGL3_CreateFontsTexture',['../class_karma_1_1_karma_gui_open_g_l_handler.html#afb5b2473fa343a6965fb971549b5b450',1,'Karma::KarmaGuiOpenGLHandler']]],
  ['karmagui_5fimplopengl3_5fcreatetexture_10',['KarmaGui_ImplOpenGL3_CreateTexture',['../class_karma_1_1_karma_gui_open_g_l_handler.html#a0c3582e02d409c5a73d75c5d99990014',1,'Karma::KarmaGuiOpenGLHandler']]],
  ['karmagui_5fimplopengl3_5fdata_11',['KarmaGui_ImplOpenGL3_Data',['../struct_karma_1_1_karma_gui___impl_open_g_l3___data.html',1,'Karma::KarmaGui_ImplOpenGL3_Data'],['../struct_karma_1_1_karma_gui___impl_open_g_l3___data.html#ae2c1a631c87d335b8e1fb24c04888af6',1,'Karma::KarmaGui_ImplOpenGL3_Data::KarmaGui_ImplOpenGL3_Data()']]],
  ['karmagui_5fimplopengl3_5fdestroydeviceobjects_12',['KarmaGui_ImplOpenGL3_DestroyDeviceObjects',['../class_karma_1_1_karma_gui_open_g_l_handler.html#ad0228fe405121a7ecee245d030455c58',1,'Karma::KarmaGuiOpenGLHandler']]],
  ['karmagui_5fimplopengl3_5fdestroyfontstexture_13',['KarmaGui_ImplOpenGL3_DestroyFontsTexture',['../class_karma_1_1_karma_gui_open_g_l_handler.html#aae7a5b8fb559412fb331525f48f3fbd1',1,'Karma::KarmaGuiOpenGLHandler']]],
  ['karmagui_5fimplopengl3_5finit_14',['KarmaGui_ImplOpenGL3_Init',['../class_karma_1_1_karma_gui_open_g_l_handler.html#a3020e8da89ed6ff2cd26d914f618df82',1,'Karma::KarmaGuiOpenGLHandler']]],
  ['karmagui_5fimplopengl3_5finitplatforminterface_15',['KarmaGui_ImplOpenGL3_InitPlatformInterface',['../class_karma_1_1_karma_gui_open_g_l_handler.html#ad2f705e51d63a8d46c49cbcab9d87acf',1,'Karma::KarmaGuiOpenGLHandler']]],
  ['karmagui_5fimplopengl3_5fnewframe_16',['KarmaGui_ImplOpenGL3_NewFrame',['../class_karma_1_1_karma_gui_open_g_l_handler.html#a9db7d56bf2d2e52c293374786f5581a4',1,'Karma::KarmaGuiOpenGLHandler']]],
  ['karmagui_5fimplopengl3_5frenderdrawdata_17',['KarmaGui_ImplOpenGL3_RenderDrawData',['../class_karma_1_1_karma_gui_open_g_l_handler.html#a4cb6956b66e5abeb43f7c7b8e13a2b84',1,'Karma::KarmaGuiOpenGLHandler']]],
  ['karmagui_5fimplopengl3_5frenderwindow_18',['KarmaGui_ImplOpenGL3_RenderWindow',['../class_karma_1_1_karma_gui_open_g_l_handler.html#a267afab4ed52edf2c7aba250fa0a5cca',1,'Karma::KarmaGuiOpenGLHandler']]],
  ['karmagui_5fimplopengl3_5fsetuprenderstate_19',['KarmaGui_ImplOpenGL3_SetupRenderState',['../class_karma_1_1_karma_gui_open_g_l_handler.html#ae092dd6c4db37e0f995150b2fc9b4370',1,'Karma::KarmaGuiOpenGLHandler']]],
  ['karmagui_5fimplopengl3_5fshutdown_20',['KarmaGui_ImplOpenGL3_Shutdown',['../class_karma_1_1_karma_gui_open_g_l_handler.html#af3bce2e43627ea8affdb7130ac9ee845',1,'Karma::KarmaGuiOpenGLHandler']]],
  ['karmagui_5fimplopengl3_5fshutdownplatforminterface_21',['KarmaGui_ImplOpenGL3_ShutdownPlatformInterface',['../class_karma_1_1_karma_gui_open_g_l_handler.html#a70d4d69bfc1d268274263585327e2e49',1,'Karma::KarmaGuiOpenGLHandler']]],
  ['karmagui_5fimplvulkan_5faddtexture_22',['KarmaGui_ImplVulkan_AddTexture',['../class_karma_1_1_karma_gui_vulkan_handler.html#a69593647c6b97022deb5449e94bdef93',1,'Karma::KarmaGuiVulkanHandler']]],
  ['karmagui_5fimplvulkan_5fcreatedescriptorsetlayout_23',['KarmaGui_ImplVulkan_CreateDescriptorSetLayout',['../class_karma_1_1_karma_gui_vulkan_handler.html#a10ede603ade2ed4ff6d9c093edb53868',1,'Karma::KarmaGuiVulkanHandler']]],
  ['karmagui_5fimplvulkan_5fcreatedeviceobjects_24',['KarmaGui_ImplVulkan_CreateDeviceObjects',['../class_karma_1_1_karma_gui_vulkan_handler.html#a8798f337eabad2a1268cfbaa6114643c',1,'Karma::KarmaGuiVulkanHandler']]],
  ['karmagui_5fimplvulkan_5fcreatefontsampler_25',['KarmaGui_ImplVulkan_CreateFontSampler',['../class_karma_1_1_karma_gui_vulkan_handler.html#aa583f5e1a61b93581443dc2382056da6',1,'Karma::KarmaGuiVulkanHandler']]],
  ['karmagui_5fimplvulkan_5fcreatefontstexture_26',['KarmaGui_ImplVulkan_CreateFontsTexture',['../class_karma_1_1_karma_gui_vulkan_handler.html#a947289d89dbaaaf49ebe72b2a834d9d7',1,'Karma::KarmaGuiVulkanHandler']]],
  ['karmagui_5fimplvulkan_5fcreateorresizewindow_27',['KarmaGui_ImplVulkan_CreateOrResizeWindow',['../class_karma_1_1_karma_gui_vulkan_handler.html#aee8565ba0b84ee6611092898b9a94d2d',1,'Karma::KarmaGuiVulkanHandler']]],
  ['karmagui_5fimplvulkan_5fcreatepipeline_28',['KarmaGui_ImplVulkan_CreatePipeline',['../class_karma_1_1_karma_gui_vulkan_handler.html#aeb43f8c13ca81df044eecbe9dbd05630',1,'Karma::KarmaGuiVulkanHandler']]],
  ['karmagui_5fimplvulkan_5fcreatepipelinelayout_29',['KarmaGui_ImplVulkan_CreatePipelineLayout',['../class_karma_1_1_karma_gui_vulkan_handler.html#ab0b7ac4443496f979c1532a8bd4a1a72',1,'Karma::KarmaGuiVulkanHandler']]],
  ['karmagui_5fimplvulkan_5fcreateshadermodules_30',['KarmaGui_ImplVulkan_CreateShaderModules',['../class_karma_1_1_karma_gui_vulkan_handler.html#abd34e93e2175ac37b4c01191aa77298b',1,'Karma::KarmaGuiVulkanHandler']]],
  ['karmagui_5fimplvulkan_5fcreatetexture_31',['KarmaGui_ImplVulkan_CreateTexture',['../class_karma_1_1_karma_gui_vulkan_handler.html#a218401e00f91c8083613f52f3b3016fa',1,'Karma::KarmaGuiVulkanHandler']]],
  ['karmagui_5fimplvulkan_5fcreatewindow_32',['KarmaGui_ImplVulkan_CreateWindow',['../class_karma_1_1_karma_gui_vulkan_handler.html#aa6bec71360e2fe60c4cea26dac3cf565',1,'Karma::KarmaGuiVulkanHandler']]],
  ['karmagui_5fimplvulkan_5fdata_33',['KarmaGui_ImplVulkan_Data',['../struct_karma_1_1_karma_gui___impl_vulkan___data.html',1,'Karma']]],
  ['karmagui_5fimplvulkan_5fdestroyallviewportsrenderbuffers_34',['KarmaGui_ImplVulkan_DestroyAllViewportsRenderBuffers',['../class_karma_1_1_karma_gui_vulkan_handler.html#a2601ed7116d9c42c98d5c9c62146fe00',1,'Karma::KarmaGuiVulkanHandler']]],
  ['karmagui_5fimplvulkan_5fdestroydeviceobjects_35',['KarmaGui_ImplVulkan_DestroyDeviceObjects',['../class_karma_1_1_karma_gui_vulkan_handler.html#a1474726a454ef471ef767f903f5551da',1,'Karma::KarmaGuiVulkanHandler']]],
  ['karmagui_5fimplvulkan_5fdestroyfontuploadobjects_36',['KarmaGui_ImplVulkan_DestroyFontUploadObjects',['../class_karma_1_1_karma_gui_vulkan_handler.html#ab0c3277122d232fe6a9bb2f8f8df477a',1,'Karma::KarmaGuiVulkanHandler']]],
  ['karmagui_5fimplvulkan_5fdestroywindow_37',['KarmaGui_ImplVulkan_DestroyWindow',['../class_karma_1_1_karma_gui_vulkan_handler.html#a42881b7018110e014a12ce23d329da65',1,'Karma::KarmaGuiVulkanHandler::KarmaGui_ImplVulkan_DestroyWindow(KarmaGuiViewport *viewport)'],['../class_karma_1_1_karma_gui_vulkan_handler.html#a4ab8fcd5e37558658567a97fc27d9e32',1,'Karma::KarmaGuiVulkanHandler::KarmaGui_ImplVulkan_DestroyWindow(KarmaGui_ImplVulkanH_Window *windowData)']]],
  ['karmagui_5fimplvulkan_5fimage_5ftexturedata_38',['KarmaGui_ImplVulkan_Image_TextureData',['../struct_karma_1_1_karma_gui___impl_vulkan___image___texture_data.html',1,'Karma::KarmaGui_ImplVulkan_Image_TextureData'],['../struct_karma_1_1_karma_gui___impl_vulkan___image___texture_data.html#a3f053b1c33ec10e8ed15e1adafaf8cbc',1,'Karma::KarmaGui_ImplVulkan_Image_TextureData::KarmaGui_ImplVulkan_Image_TextureData()']]],
  ['karmagui_5fimplvulkan_5finit_39',['KarmaGui_ImplVulkan_Init',['../class_karma_1_1_karma_gui_renderer.html#a9b480e660f6873323cbdc9b93c3d2211',1,'Karma::KarmaGuiRenderer']]],
  ['karmagui_5fimplvulkan_5finitinfo_40',['KarmaGui_ImplVulkan_InitInfo',['../struct_karma_1_1_karma_gui___impl_vulkan___init_info.html',1,'Karma']]],
  ['karmagui_5fimplvulkan_5finitplatforminterface_41',['KarmaGui_ImplVulkan_InitPlatformInterface',['../class_karma_1_1_karma_gui_vulkan_handler.html#aedb50322002e6ad8e1eb8e18356adb50',1,'Karma::KarmaGuiVulkanHandler']]],
  ['karmagui_5fimplvulkan_5fmemorytype_42',['KarmaGui_ImplVulkan_MemoryType',['../class_karma_1_1_karma_gui_vulkan_handler.html#a19d9046ecead4192278f5f15dddcca51',1,'Karma::KarmaGuiVulkanHandler']]],
  ['karmagui_5fimplvulkan_5fnewframe_43',['KarmaGui_ImplVulkan_NewFrame',['../class_karma_1_1_karma_gui_vulkan_handler.html#a4ff694292f77f635db29dd1804c13bda',1,'Karma::KarmaGuiVulkanHandler']]],
  ['karmagui_5fimplvulkan_5frenderdrawdata_44',['KarmaGui_ImplVulkan_RenderDrawData',['../class_karma_1_1_karma_gui_vulkan_handler.html#a2ca6554d0fac593aae7be85c39dab4b7',1,'Karma::KarmaGuiVulkanHandler']]],
  ['karmagui_5fimplvulkan_5frenderwindow_45',['KarmaGui_ImplVulkan_RenderWindow',['../class_karma_1_1_karma_gui_vulkan_handler.html#a72b73653d18fdde91d1225e63abf9313',1,'Karma::KarmaGuiVulkanHandler']]],
  ['karmagui_5fimplvulkan_5fsetuprenderstate_46',['KarmaGui_ImplVulkan_SetupRenderState',['../class_karma_1_1_karma_gui_vulkan_handler.html#ac989f0dd29c02b3489ff33a31c0b261b',1,'Karma::KarmaGuiVulkanHandler']]],
  ['karmagui_5fimplvulkan_5fsetwindowsize_47',['KarmaGui_ImplVulkan_SetWindowSize',['../class_karma_1_1_karma_gui_vulkan_handler.html#a2fe945584a8c6cc1b93cce469ea71961',1,'Karma::KarmaGuiVulkanHandler']]],
  ['karmagui_5fimplvulkan_5fshivaframerenderbuffers_48',['KarmaGui_ImplVulkan_ShivaFrameRenderBuffers',['../class_karma_1_1_karma_gui_vulkan_handler.html#a3f0a1ac0b54a0b7ce3896636d75a78c4',1,'Karma::KarmaGuiVulkanHandler']]],
  ['karmagui_5fimplvulkan_5fshivawindowrenderbuffers_49',['KarmaGui_ImplVulkan_ShivaWindowRenderBuffers',['../class_karma_1_1_karma_gui_vulkan_handler.html#af0fcca8d4decb19e46348685131ee6dc',1,'Karma::KarmaGuiVulkanHandler']]],
  ['karmagui_5fimplvulkan_5fshutdown_50',['KarmaGui_ImplVulkan_Shutdown',['../class_karma_1_1_karma_gui_vulkan_handler.html#a4e8f9c6e2dcc1f47adc41ed6f55370d9',1,'Karma::KarmaGuiVulkanHandler']]],
  ['karmagui_5fimplvulkan_5fshutdownplatforminterface_51',['KarmaGui_ImplVulkan_ShutdownPlatformInterface',['../class_karma_1_1_karma_gui_vulkan_handler.html#aef31ff42b26af3f3f9b7b348ca304f42',1,'Karma::KarmaGuiVulkanHandler']]],
  ['karmagui_5fimplvulkan_5fswapbuffers_52',['KarmaGui_ImplVulkan_SwapBuffers',['../class_karma_1_1_karma_gui_vulkan_handler.html#a00a73f7f1e709e8615bff7dc1e5aa00a',1,'Karma::KarmaGuiVulkanHandler']]],
  ['karmagui_5fimplvulkan_5fviewportdata_53',['KarmaGui_ImplVulkan_ViewportData',['../struct_karma_1_1_karma_gui___impl_vulkan___viewport_data.html',1,'Karma::KarmaGui_ImplVulkan_ViewportData'],['../struct_karma_1_1_karma_gui___impl_vulkan___viewport_data.html#a77a729082622d9fbd39839cb50d3f983',1,'Karma::KarmaGui_ImplVulkan_ViewportData::KarmaGui_ImplVulkan_ViewportData()']]],
  ['karmagui_5fimplvulkanh_5fimageframe_54',['KarmaGui_ImplVulkanH_ImageFrame',['../struct_karma_1_1_karma_gui___impl_vulkan_h___image_frame.html',1,'Karma']]],
  ['karmagui_5fimplvulkanh_5fimageframerenderbuffers_55',['KarmaGui_ImplVulkanH_ImageFrameRenderBuffers',['../struct_karma_1_1_karma_gui___impl_vulkan_h___image_frame_render_buffers.html',1,'Karma::KarmaGui_ImplVulkanH_ImageFrameRenderBuffers'],['../struct_karma_1_1_karma_gui___impl_vulkan_h___image_frame_render_buffers.html#a247bf694d13da4e2d260e82cd650092e',1,'Karma::KarmaGui_ImplVulkanH_ImageFrameRenderBuffers::KarmaGui_ImplVulkanH_ImageFrameRenderBuffers()']]],
  ['karmagui_5fimplvulkanh_5frhiresources_56',['KarmaGui_ImplVulkanH_RHIResources',['../struct_karma_1_1_karma_gui___impl_vulkan_h___r_h_i_resources.html',1,'Karma']]],
  ['karmagui_5fimplvulkanh_5fwindow_57',['KarmaGui_ImplVulkanH_Window',['../struct_karma_1_1_karma_gui___impl_vulkan_h___window.html',1,'Karma::KarmaGui_ImplVulkanH_Window'],['../struct_karma_1_1_karma_gui___impl_vulkan_h___window.html#a194b19fa100ff3c1f8399110f43d1346',1,'Karma::KarmaGui_ImplVulkanH_Window::KarmaGui_ImplVulkanH_Window()']]],
  ['karmagui_5fimplvulkanh_5fwindowrenderbuffers_58',['KarmaGui_ImplVulkanH_WindowRenderBuffers',['../struct_karma_1_1_karma_gui___impl_vulkan_h___window_render_buffers.html',1,'Karma']]],
  ['karmagui_5foffscreen_5frender_5fresources_59',['KarmaGui_OffScreen_Render_Resources',['../struct_karma_1_1_karma_gui___off_screen___render___resources.html',1,'Karma']]],
  ['karmagui_5ftexture_60',['KarmaGui_Texture',['../struct_karma_1_1_karma_gui__3_d_scene___to__2_d_texture___data.html#aea53a626172544be735106eed0830770',1,'Karma::KarmaGui_3DScene_To_2DTexture_Data']]],
  ['karmagui_5fvulkan_5fframe_5fon_5fflight_61',['KarmaGui_Vulkan_Frame_On_Flight',['../struct_karma_1_1_karma_gui___vulkan___frame___on___flight.html',1,'Karma']]],
  ['karmaguibackendrendereruserdata_62',['KarmaGuiBackendRendererUserData',['../struct_karma_1_1_karma_gui_backend_renderer_user_data.html',1,'Karma']]],
  ['karmaguicontext_63',['KarmaGuiContext',['../struct_karma_gui_context.html',1,'']]],
  ['karmaguidockcontextprunenodedata_64',['KarmaGuiDockContextPruneNodeData',['../struct_karma_gui_dock_context_prune_node_data.html',1,'']]],
  ['karmaguidocknodetreeinfo_65',['KarmaGuiDockNodeTreeInfo',['../struct_karma_gui_dock_node_tree_info.html',1,'']]],
  ['karmaguidockpreviewdata_66',['KarmaGuiDockPreviewData',['../struct_karma_gui_dock_preview_data.html',1,'']]],
  ['karmaguiinputtextcallbackdata_67',['KarmaGuiInputTextCallbackData',['../struct_karma_gui_input_text_callback_data.html',1,'']]],
  ['karmaguiinternal_68',['KarmaGuiInternal',['../class_karma_1_1_karma_gui_internal.html',1,'Karma']]],
  ['karmaguiinternal_2eh_69',['KarmaGuiInternal.h',['../_karma_gui_internal_8h.html',1,'']]],
  ['karmaguiio_70',['KarmaGuiIO',['../struct_karma_gui_i_o.html',1,'']]],
  ['karmaguikeydata_71',['KarmaGuiKeyData',['../struct_karma_gui_key_data.html',1,'']]],
  ['karmaguilayer_72',['KarmaGuiLayer',['../class_karma_1_1_karma_gui_layer.html',1,'Karma']]],
  ['karmaguilayer_2eh_73',['KarmaGuiLayer.h',['../_karma_gui_layer_8h.html',1,'']]],
  ['karmaguilistclipper_74',['KarmaGuiListClipper',['../struct_karma_gui_list_clipper.html',1,'']]],
  ['karmaguionceuponaframe_75',['KarmaGuiOnceUponAFrame',['../struct_karma_gui_once_upon_a_frame.html',1,'']]],
  ['karmaguiopenglhandler_76',['KarmaGuiOpenGLHandler',['../class_karma_1_1_karma_gui_open_g_l_handler.html',1,'Karma']]],
  ['karmaguiopenglhandler_2eh_77',['KarmaGuiOpenGLHandler.h',['../_karma_gui_open_g_l_handler_8h.html',1,'']]],
  ['karmaguipayload_78',['KarmaGuiPayload',['../struct_karma_gui_payload.html',1,'']]],
  ['karmaguiplatformimedata_79',['KarmaGuiPlatformImeData',['../struct_karma_gui_platform_ime_data.html',1,'']]],
  ['karmaguiplatformio_80',['KarmaGuiPlatformIO',['../struct_karma_gui_platform_i_o.html',1,'']]],
  ['karmaguiplatformmonitor_81',['KarmaGuiPlatformMonitor',['../struct_karma_gui_platform_monitor.html',1,'']]],
  ['karmaguiplotarraygetterdata_82',['KarmaGuiPlotArrayGetterData',['../struct_karma_gui_plot_array_getter_data.html',1,'']]],
  ['karmaguirender_83',['KarmaGuiRender',['../class_karma_1_1_karma_gui_layer.html#a80cc8aad61a5ade3541b05557f21edc4',1,'Karma::KarmaGuiLayer::KarmaGuiRender()'],['../class_karma_1_1_layer.html#ab81fb12810d36567ed37af322ef28dea',1,'Karma::Layer::KarmaGuiRender()']]],
  ['karmaguirenderer_84',['KarmaGuiRenderer',['../class_karma_1_1_karma_gui_renderer.html',1,'Karma']]],
  ['karmaguirenderer_2eh_85',['KarmaGuiRenderer.h',['../_karma_gui_renderer_8h.html',1,'']]],
  ['karmaguiresizeborderdef_86',['KarmaGuiResizeBorderDef',['../struct_karma_gui_resize_border_def.html',1,'']]],
  ['karmaguiresizegripdef_87',['KarmaGuiResizeGripDef',['../struct_karma_gui_resize_grip_def.html',1,'']]],
  ['karmaguisizecallbackdata_88',['KarmaGuiSizeCallbackData',['../struct_karma_gui_size_callback_data.html',1,'']]],
  ['karmaguistorage_89',['KarmaGuiStorage',['../struct_karma_gui_storage.html',1,'']]],
  ['karmaguistyle_90',['KarmaGuiStyle',['../struct_karma_gui_style.html',1,'']]],
  ['karmaguistylevarinfo_91',['KarmaGuiStyleVarInfo',['../struct_karma_gui_style_var_info.html',1,'']]],
  ['karmaguitabbarsection_92',['KarmaGuiTabBarSection',['../struct_karma_gui_tab_bar_section.html',1,'']]],
  ['karmaguitablecolumnsortspecs_93',['KarmaGuiTableColumnSortSpecs',['../struct_karma_gui_table_column_sort_specs.html',1,'']]],
  ['karmaguitablesortspecs_94',['KarmaGuiTableSortSpecs',['../struct_karma_gui_table_sort_specs.html',1,'']]],
  ['karmaguitextbuffer_95',['KarmaGuiTextBuffer',['../struct_karma_gui_text_buffer.html',1,'']]],
  ['karmaguitextfilter_96',['KarmaGuiTextFilter',['../struct_karma_gui_text_filter.html',1,'']]],
  ['karmaguiviewport_97',['KarmaGuiViewport',['../struct_karma_gui_viewport.html',1,'']]],
  ['karmaguivulkanhandler_98',['KarmaGuiVulkanHandler',['../class_karma_1_1_karma_gui_vulkan_handler.html',1,'Karma']]],
  ['karmaguivulkanhandler_2eh_99',['KarmaGuiVulkanHandler.h',['../_karma_gui_vulkan_handler_8h.html',1,'']]],
  ['karmaguiwindowclass_100',['KarmaGuiWindowClass',['../struct_karma_gui_window_class.html',1,'']]],
  ['karmamap_101',['KarmaMap',['../class_karma_map.html',1,'KarmaMap&lt; KeyType, ValueType &gt;'],['../class_karma_map.html#ab42fcf49ef01f648342cf924319e9ffe',1,'KarmaMap::KarmaMap()']]],
  ['karmamap_3c_20uclass_20_2a_2c_20karmavector_3c_20uobject_20_2a_20_3e_20_2a_20_3e_102',['KarmaMap&lt; UClass *, KarmaVector&lt; UObject * &gt; * &gt;',['../class_karma_map.html',1,'']]],
  ['karmamap_3c_20vkdescriptortype_2c_20uint32_5ft_20_3e_103',['KarmaMap&lt; VkDescriptorType, uint32_t &gt;',['../class_karma_map.html',1,'']]],
  ['karmamath_2eh_104',['KarmaMath.h',['../_karma_math_8h.html',1,'']]],
  ['karmamemory_2eh_105',['KarmaMemory.h',['../_karma_memory_8h.html',1,'']]],
  ['karmarhi_2eh_106',['KarmaRHI.h',['../_karma_r_h_i_8h.html',1,'']]],
  ['karmasmriti_107',['KarmaSmriti',['../class_karma_1_1_karma_smriti.html',1,'Karma::KarmaSmriti'],['../class_karma_1_1_karma_smriti.html#a3f449d4101020b9a5f79e551e6345ab8',1,'Karma::KarmaSmriti::KarmaSmriti()']]],
  ['karmasmriti_2eh_108',['KarmaSmriti.h',['../_karma_smriti_8h.html',1,'']]],
  ['karmastbtextedit_2eh_109',['KarmaSTBTextEdit.h',['../_karma_s_t_b_text_edit_8h.html',1,'']]],
  ['karmatypes_2eh_110',['KarmaTypes.h',['../_karma_types_8h.html',1,'']]],
  ['karmautilities_111',['KarmaUtilities',['../class_karma_1_1_karma_utilities.html',1,'Karma']]],
  ['karmautilities_2eh_112',['KarmaUtilities.h',['../_karma_utilities_8h.html',1,'']]],
  ['karmavector_113',['KarmaVector',['../class_karma_vector.html',1,'KarmaVector&lt; BuildingBlock &gt;'],['../class_karma_vector.html#a2a6f1cd06e52515f0f8b9f5fad083116',1,'KarmaVector::KarmaVector()']]],
  ['karmavector_3c_20class_20karma_3a_3afvulkandescriptorpool_20_2a_20_3e_114',['KarmaVector&lt; class Karma::FVulkanDescriptorPool * &gt;',['../class_karma_vector.html',1,'']]],
  ['karmavector_3c_20fuobjectallocatorcallback_20_3e_115',['KarmaVector&lt; FUObjectAllocatorCallback &gt;',['../class_karma_vector.html',1,'']]],
  ['karmavector_3c_20fuobjectitem_20_2a_20_3e_116',['KarmaVector&lt; FUObjectItem * &gt;',['../class_karma_vector.html',1,'']]],
  ['karmavector_3c_20karma_3a_3aaactor_20_2a_20_3e_117',['KarmaVector&lt; Karma::AActor * &gt;',['../class_karma_vector.html',1,'']]],
  ['karmavector_3c_20karma_3a_3afvulkandescriptorsets_20_2a_20_3e_118',['KarmaVector&lt; Karma::FVulkanDescriptorSets * &gt;',['../class_karma_vector.html',1,'']]],
  ['karmavector_3c_20karma_3a_3afvulkandescriptorsetslayoutinfo_3a_3afsetlayout_20_3e_119',['KarmaVector&lt; Karma::FVulkanDescriptorSetsLayoutInfo::FSetLayout &gt;',['../class_karma_vector.html',1,'']]],
  ['karmavector_3c_20karma_3a_3afvulkanfence_20_2a_20_3e_120',['KarmaVector&lt; Karma::FVulkanFence * &gt;',['../class_karma_vector.html',1,'']]],
  ['karmavector_3c_20karma_3a_3afvulkanframebuffer_20_2a_20_3e_121',['KarmaVector&lt; Karma::FVulkanFramebuffer * &gt;',['../class_karma_vector.html',1,'']]],
  ['karmavector_3c_20karma_3a_3afvulkanrenderpassinfo_3a_3afattachmentinfo_20_3e_122',['KarmaVector&lt; Karma::FVulkanRenderPassInfo::FAttachmentInfo &gt;',['../class_karma_vector.html',1,'']]],
  ['karmavector_3c_20karma_3a_3afvulkanrenderpassinfo_3a_3afattachmentrefinfo_20_3e_123',['KarmaVector&lt; Karma::FVulkanRenderPassInfo::FAttachmentRefInfo &gt;',['../class_karma_vector.html',1,'']]],
  ['karmavector_3c_20karma_3a_3afvulkanrendertargetsinfo_20_2a_20_3e_124',['KarmaVector&lt; Karma::FVulkanRenderTargetsInfo * &gt;',['../class_karma_vector.html',1,'']]],
  ['karmavector_3c_20karma_3a_3afworldcontext_20_2a_20_3e_125',['KarmaVector&lt; Karma::FWorldContext * &gt;',['../class_karma_vector.html',1,'']]],
  ['karmavector_3c_20karma_3a_3auobject_20_2a_20_3e_126',['KarmaVector&lt; Karma::UObject * &gt;',['../class_karma_vector.html',1,'']]],
  ['karmavector_3c_20karma_3a_3auworld_20_2a_2a_20_3e_127',['KarmaVector&lt; Karma::UWorld ** &gt;',['../class_karma_vector.html',1,'']]],
  ['karmavector_3c_20karmavector_3c_20vkdescriptorset_20_3e_20_3e_128',['KarmaVector&lt; KarmaVector&lt; VkDescriptorSet &gt; &gt;',['../class_karma_vector.html',1,'']]],
  ['karmavector_3c_20std_3a_3ashared_5fptr_3c_20karma_3a_3auactorcomponent_20_3e_20_3e_129',['KarmaVector&lt; std::shared_ptr&lt; Karma::UActorComponent &gt; &gt;',['../class_karma_vector.html',1,'']]],
  ['karmavector_3c_20tattachmentdescriptionclass_20_3e_130',['KarmaVector&lt; TAttachmentDescriptionClass &gt;',['../class_karma_vector.html',1,'']]],
  ['karmavector_3c_20tattachmentreferenceclass_20_3e_131',['KarmaVector&lt; TAttachmentReferenceClass &gt;',['../class_karma_vector.html',1,'']]],
  ['karmavector_3c_20uint32_5ft_20_3e_132',['KarmaVector&lt; uint32_t &gt;',['../class_karma_vector.html',1,'']]],
  ['karmavector_3c_20vkdescriptorsetlayout_20_3e_133',['KarmaVector&lt; VkDescriptorSetLayout &gt;',['../class_karma_vector.html',1,'']]],
  ['karmavector_3c_20vkdescriptorsetlayoutbinding_20_3e_134',['KarmaVector&lt; VkDescriptorSetLayoutBinding &gt;',['../class_karma_vector.html',1,'']]],
  ['karmavector_3c_20vkimageview_20_3e_135',['KarmaVector&lt; VkImageView &gt;',['../class_karma_vector.html',1,'']]],
  ['kengine_136',['KEngine',['../class_karma_1_1_k_engine.html',1,'Karma::KEngine'],['../class_karma_1_1_k_engine.html#a2d82337d43a4dea3696b6162a445d512',1,'Karma::KEngine::KEngine()']]],
  ['keyevent_137',['KeyEvent',['../class_karma_1_1_key_event.html',1,'Karma::KeyEvent'],['../class_karma_1_1_key_event.html#aaaa1e581cda1319a62c536f61d858568',1,'Karma::KeyEvent::KeyEvent()']]],
  ['keyevent_2eh_138',['KeyEvent.h',['../_key_event_8h.html',1,'']]],
  ['keypressedevent_139',['KeyPressedEvent',['../class_karma_1_1_key_pressed_event.html',1,'Karma::KeyPressedEvent'],['../class_karma_1_1_key_pressed_event.html#a8b3881e519f1d2c0df050da3e7cd30fa',1,'Karma::KeyPressedEvent::KeyPressedEvent()']]],
  ['keyreleasedevent_140',['KeyReleasedEvent',['../class_karma_1_1_key_released_event.html',1,'Karma::KeyReleasedEvent'],['../class_karma_1_1_key_released_event.html#a1c599f02084537537bfde34cc2fce593',1,'Karma::KeyReleasedEvent::KeyReleasedEvent()']]],
  ['keytypedevent_141',['KeyTypedEvent',['../class_karma_1_1_key_typed_event.html',1,'Karma::KeyTypedEvent'],['../class_karma_1_1_key_typed_event.html#a28e7528d39c101e08f3d5e7874997553',1,'Karma::KeyTypedEvent::KeyTypedEvent()']]],
  ['kgbitarray_142',['KGBitArray',['../struct_k_g_bit_array.html',1,'']]],
  ['kgbitarray_3c_20kgguikey_5fnamedkey_5fcount_2c_20_2dkgguikey_5fnamedkey_5fbegin_20_3e_143',['KGBitArray&lt; KGGuiKey_NamedKey_COUNT, -KGGuiKey_NamedKey_BEGIN &gt;',['../struct_k_g_bit_array.html',1,'']]],
  ['kgbitvector_144',['KGBitVector',['../struct_k_g_bit_vector.html',1,'']]],
  ['kgchunkstream_145',['KGChunkStream',['../struct_k_g_chunk_stream.html',1,'']]],
  ['kgchunkstream_3c_20kgguitablesettings_20_3e_146',['KGChunkStream&lt; KGGuiTableSettings &gt;',['../struct_k_g_chunk_stream.html',1,'']]],
  ['kgchunkstream_3c_20kgguiwindowsettings_20_3e_147',['KGChunkStream&lt; KGGuiWindowSettings &gt;',['../struct_k_g_chunk_stream.html',1,'']]],
  ['kgcolor_148',['KGColor',['../struct_k_g_color.html',1,'']]],
  ['kgdrawchannel_149',['KGDrawChannel',['../struct_k_g_draw_channel.html',1,'']]],
  ['kgdrawcmd_150',['KGDrawCmd',['../struct_k_g_draw_cmd.html',1,'']]],
  ['kgdrawcmdheader_151',['KGDrawCmdHeader',['../struct_k_g_draw_cmd_header.html',1,'']]],
  ['kgdrawdata_152',['KGDrawData',['../struct_k_g_draw_data.html',1,'']]],
  ['kgdrawdatabuilder_153',['KGDrawDataBuilder',['../struct_k_g_draw_data_builder.html',1,'']]],
  ['kgdrawlist_154',['KGDrawList',['../struct_k_g_draw_list.html',1,'']]],
  ['kgdrawlistshareddata_155',['KGDrawListSharedData',['../struct_k_g_draw_list_shared_data.html',1,'']]],
  ['kgdrawlistsplitter_156',['KGDrawListSplitter',['../struct_k_g_draw_list_splitter.html',1,'']]],
  ['kgdrawvert_157',['KGDrawVert',['../struct_k_g_draw_vert.html',1,'']]],
  ['kgfont_158',['KGFont',['../struct_k_g_font.html',1,'']]],
  ['kgfontatlas_159',['KGFontAtlas',['../struct_k_g_font_atlas.html',1,'']]],
  ['kgfontatlascustomrect_160',['KGFontAtlasCustomRect',['../struct_k_g_font_atlas_custom_rect.html',1,'']]],
  ['kgfontbuilddstdata_161',['KGFontBuildDstData',['../struct_k_g_font_build_dst_data.html',1,'']]],
  ['kgfontbuilderio_162',['KGFontBuilderIO',['../struct_k_g_font_builder_i_o.html',1,'']]],
  ['kgfontbuildsrcdata_163',['KGFontBuildSrcData',['../struct_k_g_font_build_src_data.html',1,'']]],
  ['kgfontconfig_164',['KGFontConfig',['../struct_k_g_font_config.html',1,'']]],
  ['kgfontglyph_165',['KGFontGlyph',['../struct_k_g_font_glyph.html',1,'']]],
  ['kgfontglyphrangesbuilder_166',['KGFontGlyphRangesBuilder',['../struct_k_g_font_glyph_ranges_builder.html',1,'']]],
  ['kgguicolormod_167',['KGGuiColorMod',['../struct_k_g_gui_color_mod.html',1,'']]],
  ['kgguicombopreviewdata_168',['KGGuiComboPreviewData',['../struct_k_g_gui_combo_preview_data.html',1,'']]],
  ['kgguicontexthook_169',['KGGuiContextHook',['../struct_k_g_gui_context_hook.html',1,'']]],
  ['kgguidatatypeinfo_170',['KGGuiDataTypeInfo',['../struct_k_g_gui_data_type_info.html',1,'']]],
  ['kgguidatatypetempstorage_171',['KGGuiDataTypeTempStorage',['../struct_k_g_gui_data_type_temp_storage.html',1,'']]],
  ['kgguidockcontext_172',['KGGuiDockContext',['../struct_k_g_gui_dock_context.html',1,'']]],
  ['kgguidocknode_173',['KGGuiDockNode',['../struct_k_g_gui_dock_node.html',1,'']]],
  ['kgguidocknodesettings_174',['KGGuiDockNodeSettings',['../struct_k_g_gui_dock_node_settings.html',1,'']]],
  ['kgguidockrequest_175',['KGGuiDockRequest',['../struct_k_g_gui_dock_request.html',1,'']]],
  ['kgguigroupdata_176',['KGGuiGroupData',['../struct_k_g_gui_group_data.html',1,'']]],
  ['kgguiinputevent_177',['KGGuiInputEvent',['../struct_k_g_gui_input_event.html',1,'']]],
  ['kgguiinputeventappfocused_178',['KGGuiInputEventAppFocused',['../struct_k_g_gui_input_event_app_focused.html',1,'']]],
  ['kgguiinputeventkey_179',['KGGuiInputEventKey',['../struct_k_g_gui_input_event_key.html',1,'']]],
  ['kgguiinputeventmousebutton_180',['KGGuiInputEventMouseButton',['../struct_k_g_gui_input_event_mouse_button.html',1,'']]],
  ['kgguiinputeventmousepos_181',['KGGuiInputEventMousePos',['../struct_k_g_gui_input_event_mouse_pos.html',1,'']]],
  ['kgguiinputeventmouseviewport_182',['KGGuiInputEventMouseViewport',['../struct_k_g_gui_input_event_mouse_viewport.html',1,'']]],
  ['kgguiinputeventmousewheel_183',['KGGuiInputEventMouseWheel',['../struct_k_g_gui_input_event_mouse_wheel.html',1,'']]],
  ['kgguiinputeventtext_184',['KGGuiInputEventText',['../struct_k_g_gui_input_event_text.html',1,'']]],
  ['kgguiinputtextstate_185',['KGGuiInputTextState',['../struct_k_g_gui_input_text_state.html',1,'']]],
  ['kgguikeyownerdata_186',['KGGuiKeyOwnerData',['../struct_k_g_gui_key_owner_data.html',1,'']]],
  ['kgguikeyroutingdata_187',['KGGuiKeyRoutingData',['../struct_k_g_gui_key_routing_data.html',1,'']]],
  ['kgguikeyroutingtable_188',['KGGuiKeyRoutingTable',['../struct_k_g_gui_key_routing_table.html',1,'']]],
  ['kgguilastitemdata_189',['KGGuiLastItemData',['../struct_k_g_gui_last_item_data.html',1,'']]],
  ['kgguilistclipperdata_190',['KGGuiListClipperData',['../struct_k_g_gui_list_clipper_data.html',1,'']]],
  ['kgguilistclipperrange_191',['KGGuiListClipperRange',['../struct_k_g_gui_list_clipper_range.html',1,'']]],
  ['kgguilocentry_192',['KGGuiLocEntry',['../struct_k_g_gui_loc_entry.html',1,'']]],
  ['kgguimenucolumns_193',['KGGuiMenuColumns',['../struct_k_g_gui_menu_columns.html',1,'']]],
  ['kgguimetricsconfig_194',['KGGuiMetricsConfig',['../struct_k_g_gui_metrics_config.html',1,'']]],
  ['kgguinavitemdata_195',['KGGuiNavItemData',['../struct_k_g_gui_nav_item_data.html',1,'']]],
  ['kgguinextitemdata_196',['KGGuiNextItemData',['../struct_k_g_gui_next_item_data.html',1,'']]],
  ['kgguinextwindowdata_197',['KGGuiNextWindowData',['../struct_k_g_gui_next_window_data.html',1,'']]],
  ['kgguioldcolumndata_198',['KGGuiOldColumnData',['../struct_k_g_gui_old_column_data.html',1,'']]],
  ['kgguioldcolumns_199',['KGGuiOldColumns',['../struct_k_g_gui_old_columns.html',1,'']]],
  ['kgguipopupdata_200',['KGGuiPopupData',['../struct_k_g_gui_popup_data.html',1,'']]],
  ['kgguiptrorindex_201',['KGGuiPtrOrIndex',['../struct_k_g_gui_ptr_or_index.html',1,'']]],
  ['kgguisettingshandler_202',['KGGuiSettingsHandler',['../struct_k_g_gui_settings_handler.html',1,'']]],
  ['kgguishrinkwidthitem_203',['KGGuiShrinkWidthItem',['../struct_k_g_gui_shrink_width_item.html',1,'']]],
  ['kgguistacklevelinfo_204',['KGGuiStackLevelInfo',['../struct_k_g_gui_stack_level_info.html',1,'']]],
  ['kgguistacksizes_205',['KGGuiStackSizes',['../struct_k_g_gui_stack_sizes.html',1,'']]],
  ['kgguistacktool_206',['KGGuiStackTool',['../struct_k_g_gui_stack_tool.html',1,'']]],
  ['kgguistylemod_207',['KGGuiStyleMod',['../struct_k_g_gui_style_mod.html',1,'']]],
  ['kgguitabbar_208',['KGGuiTabBar',['../struct_k_g_gui_tab_bar.html',1,'']]],
  ['kgguitabitem_209',['KGGuiTabItem',['../struct_k_g_gui_tab_item.html',1,'']]],
  ['kgguitable_210',['KGGuiTable',['../struct_k_g_gui_table.html',1,'']]],
  ['kgguitablecelldata_211',['KGGuiTableCellData',['../struct_k_g_gui_table_cell_data.html',1,'']]],
  ['kgguitablecolumn_212',['KGGuiTableColumn',['../struct_k_g_gui_table_column.html',1,'']]],
  ['kgguitablecolumnsettings_213',['KGGuiTableColumnSettings',['../struct_k_g_gui_table_column_settings.html',1,'']]],
  ['kgguitableinstancedata_214',['KGGuiTableInstanceData',['../struct_k_g_gui_table_instance_data.html',1,'']]],
  ['kgguitablesettings_215',['KGGuiTableSettings',['../struct_k_g_gui_table_settings.html',1,'']]],
  ['kgguitabletempdata_216',['KGGuiTableTempData',['../struct_k_g_gui_table_temp_data.html',1,'']]],
  ['kgguitextindex_217',['KGGuiTextIndex',['../struct_k_g_gui_text_index.html',1,'']]],
  ['kgguiviewportp_218',['KGGuiViewportP',['../struct_k_g_gui_viewport_p.html',1,'']]],
  ['kgguiwindow_219',['KGGuiWindow',['../struct_k_g_gui_window.html',1,'']]],
  ['kgguiwindowdockstyle_220',['KGGuiWindowDockStyle',['../struct_k_g_gui_window_dock_style.html',1,'']]],
  ['kgguiwindowsettings_221',['KGGuiWindowSettings',['../struct_k_g_gui_window_settings.html',1,'']]],
  ['kgguiwindowstackdata_222',['KGGuiWindowStackData',['../struct_k_g_gui_window_stack_data.html',1,'']]],
  ['kgguiwindowtempdata_223',['KGGuiWindowTempData',['../struct_k_g_gui_window_temp_data.html',1,'']]],
  ['kgnewwrapper_224',['KGNewWrapper',['../struct_k_g_new_wrapper.html',1,'']]],
  ['kgpool_225',['KGPool',['../struct_k_g_pool.html',1,'']]],
  ['kgpool_3c_20kgguitabbar_20_3e_226',['KGPool&lt; KGGuiTabBar &gt;',['../struct_k_g_pool.html',1,'']]],
  ['kgpool_3c_20kgguitable_20_3e_227',['KGPool&lt; KGGuiTable &gt;',['../struct_k_g_pool.html',1,'']]],
  ['kgrect_228',['KGRect',['../struct_k_g_rect.html',1,'']]],
  ['kgspan_229',['KGSpan',['../struct_k_g_span.html',1,'']]],
  ['kgspan_3c_20kgguitablecelldata_20_3e_230',['KGSpan&lt; KGGuiTableCellData &gt;',['../struct_k_g_span.html',1,'']]],
  ['kgspan_3c_20kgguitablecolumn_20_3e_231',['KGSpan&lt; KGGuiTableColumn &gt;',['../struct_k_g_span.html',1,'']]],
  ['kgspan_3c_20kgguitablecolumnidx_20_3e_232',['KGSpan&lt; KGGuiTableColumnIdx &gt;',['../struct_k_g_span.html',1,'']]],
  ['kgspanallocator_233',['KGSpanAllocator',['../struct_k_g_span_allocator.html',1,'']]],
  ['kgvec1_234',['KGVec1',['../struct_k_g_vec1.html',1,'']]],
  ['kgvec2_235',['KGVec2',['../struct_k_g_vec2.html',1,'']]],
  ['kgvec2ih_236',['KGVec2ih',['../struct_k_g_vec2ih.html',1,'']]],
  ['kgvec4_237',['KGVec4',['../struct_k_g_vec4.html',1,'']]],
  ['kgvector_238',['KGVector',['../struct_k_g_vector.html',1,'']]],
  ['kgvector_3c_20char_20_3e_239',['KGVector&lt; char &gt;',['../struct_k_g_vector.html',1,'']]],
  ['kgvector_3c_20float_20_3e_240',['KGVector&lt; float &gt;',['../struct_k_g_vector.html',1,'']]],
  ['kgvector_3c_20int_20_3e_241',['KGVector&lt; int &gt;',['../struct_k_g_vector.html',1,'']]],
  ['kgvector_3c_20karmaguiplatformmonitor_20_3e_242',['KGVector&lt; KarmaGuiPlatformMonitor &gt;',['../struct_k_g_vector.html',1,'']]],
  ['kgvector_3c_20karmaguistorage_3a_3aimguistoragepair_20_3e_243',['KGVector&lt; KarmaGuiStorage::ImGuiStoragePair &gt;',['../struct_k_g_vector.html',1,'']]],
  ['kgvector_3c_20karmaguitablecolumnsortspecs_20_3e_244',['KGVector&lt; KarmaGuiTableColumnSortSpecs &gt;',['../struct_k_g_vector.html',1,'']]],
  ['kgvector_3c_20karmaguitextfilter_3a_3aimguitextrange_20_3e_245',['KGVector&lt; KarmaGuiTextFilter::ImGuiTextRange &gt;',['../struct_k_g_vector.html',1,'']]],
  ['kgvector_3c_20karmaguiviewport_20_2a_20_3e_246',['KGVector&lt; KarmaGuiViewport * &gt;',['../struct_k_g_vector.html',1,'']]],
  ['kgvector_3c_20kgdrawchannel_20_3e_247',['KGVector&lt; KGDrawChannel &gt;',['../struct_k_g_vector.html',1,'']]],
  ['kgvector_3c_20kgdrawcmd_20_3e_248',['KGVector&lt; KGDrawCmd &gt;',['../struct_k_g_vector.html',1,'']]],
  ['kgvector_3c_20kgdrawidx_20_3e_249',['KGVector&lt; KGDrawIdx &gt;',['../struct_k_g_vector.html',1,'']]],
  ['kgvector_3c_20kgdrawlist_20_2a_20_3e_250',['KGVector&lt; KGDrawList * &gt;',['../struct_k_g_vector.html',1,'']]],
  ['kgvector_3c_20kgdrawvert_20_3e_251',['KGVector&lt; KGDrawVert &gt;',['../struct_k_g_vector.html',1,'']]],
  ['kgvector_3c_20kgfont_20_2a_20_3e_252',['KGVector&lt; KGFont * &gt;',['../struct_k_g_vector.html',1,'']]],
  ['kgvector_3c_20kgfontatlascustomrect_20_3e_253',['KGVector&lt; KGFontAtlasCustomRect &gt;',['../struct_k_g_vector.html',1,'']]],
  ['kgvector_3c_20kgfontconfig_20_3e_254',['KGVector&lt; KGFontConfig &gt;',['../struct_k_g_vector.html',1,'']]],
  ['kgvector_3c_20kgfontglyph_20_3e_255',['KGVector&lt; KGFontGlyph &gt;',['../struct_k_g_vector.html',1,'']]],
  ['kgvector_3c_20kgguicolormod_20_3e_256',['KGVector&lt; KGGuiColorMod &gt;',['../struct_k_g_vector.html',1,'']]],
  ['kgvector_3c_20kgguicontexthook_20_3e_257',['KGVector&lt; KGGuiContextHook &gt;',['../struct_k_g_vector.html',1,'']]],
  ['kgvector_3c_20kgguidocknodesettings_20_3e_258',['KGVector&lt; KGGuiDockNodeSettings &gt;',['../struct_k_g_vector.html',1,'']]],
  ['kgvector_3c_20kgguidockrequest_20_3e_259',['KGVector&lt; KGGuiDockRequest &gt;',['../struct_k_g_vector.html',1,'']]],
  ['kgvector_3c_20kgguigroupdata_20_3e_260',['KGVector&lt; KGGuiGroupData &gt;',['../struct_k_g_vector.html',1,'']]],
  ['kgvector_3c_20kgguiid_20_3e_261',['KGVector&lt; KGGuiID &gt;',['../struct_k_g_vector.html',1,'']]],
  ['kgvector_3c_20kgguiinputevent_20_3e_262',['KGVector&lt; KGGuiInputEvent &gt;',['../struct_k_g_vector.html',1,'']]],
  ['kgvector_3c_20kgguiitemflags_20_3e_263',['KGVector&lt; KGGuiItemFlags &gt;',['../struct_k_g_vector.html',1,'']]],
  ['kgvector_3c_20kgguikeyroutingdata_20_3e_264',['KGVector&lt; KGGuiKeyRoutingData &gt;',['../struct_k_g_vector.html',1,'']]],
  ['kgvector_3c_20kgguilistclipperdata_20_3e_265',['KGVector&lt; KGGuiListClipperData &gt;',['../struct_k_g_vector.html',1,'']]],
  ['kgvector_3c_20kgguilistclipperrange_20_3e_266',['KGVector&lt; KGGuiListClipperRange &gt;',['../struct_k_g_vector.html',1,'']]],
  ['kgvector_3c_20kgguioldcolumndata_20_3e_267',['KGVector&lt; KGGuiOldColumnData &gt;',['../struct_k_g_vector.html',1,'']]],
  ['kgvector_3c_20kgguioldcolumns_20_3e_268',['KGVector&lt; KGGuiOldColumns &gt;',['../struct_k_g_vector.html',1,'']]],
  ['kgvector_3c_20kgguipopupdata_20_3e_269',['KGVector&lt; KGGuiPopupData &gt;',['../struct_k_g_vector.html',1,'']]],
  ['kgvector_3c_20kgguiptrorindex_20_3e_270',['KGVector&lt; KGGuiPtrOrIndex &gt;',['../struct_k_g_vector.html',1,'']]],
  ['kgvector_3c_20kgguisettingshandler_20_3e_271',['KGVector&lt; KGGuiSettingsHandler &gt;',['../struct_k_g_vector.html',1,'']]],
  ['kgvector_3c_20kgguishrinkwidthitem_20_3e_272',['KGVector&lt; KGGuiShrinkWidthItem &gt;',['../struct_k_g_vector.html',1,'']]],
  ['kgvector_3c_20kgguistacklevelinfo_20_3e_273',['KGVector&lt; KGGuiStackLevelInfo &gt;',['../struct_k_g_vector.html',1,'']]],
  ['kgvector_3c_20kgguistylemod_20_3e_274',['KGVector&lt; KGGuiStyleMod &gt;',['../struct_k_g_vector.html',1,'']]],
  ['kgvector_3c_20kgguitabbar_20_3e_275',['KGVector&lt; KGGuiTabBar &gt;',['../struct_k_g_vector.html',1,'']]],
  ['kgvector_3c_20kgguitabitem_20_3e_276',['KGVector&lt; KGGuiTabItem &gt;',['../struct_k_g_vector.html',1,'']]],
  ['kgvector_3c_20kgguitable_20_3e_277',['KGVector&lt; KGGuiTable &gt;',['../struct_k_g_vector.html',1,'']]],
  ['kgvector_3c_20kgguitableinstancedata_20_3e_278',['KGVector&lt; KGGuiTableInstanceData &gt;',['../struct_k_g_vector.html',1,'']]],
  ['kgvector_3c_20kgguitabletempdata_20_3e_279',['KGVector&lt; KGGuiTableTempData &gt;',['../struct_k_g_vector.html',1,'']]],
  ['kgvector_3c_20kgguiviewportp_20_2a_20_3e_280',['KGVector&lt; KGGuiViewportP * &gt;',['../struct_k_g_vector.html',1,'']]],
  ['kgvector_3c_20kgguiwindow_20_2a_20_3e_281',['KGVector&lt; KGGuiWindow * &gt;',['../struct_k_g_vector.html',1,'']]],
  ['kgvector_3c_20kgguiwindowstackdata_20_3e_282',['KGVector&lt; KGGuiWindowStackData &gt;',['../struct_k_g_vector.html',1,'']]],
  ['kgvector_3c_20kgtextureid_20_3e_283',['KGVector&lt; KGTextureID &gt;',['../struct_k_g_vector.html',1,'']]],
  ['kgvector_3c_20kgu32_20_3e_284',['KGVector&lt; KGU32 &gt;',['../struct_k_g_vector.html',1,'']]],
  ['kgvector_3c_20kgvec2_20_3e_285',['KGVector&lt; KGVec2 &gt;',['../struct_k_g_vector.html',1,'']]],
  ['kgvector_3c_20kgvec4_20_3e_286',['KGVector&lt; KGVec4 &gt;',['../struct_k_g_vector.html',1,'']]],
  ['kgvector_3c_20kgwchar_20_3e_287',['KGVector&lt; KGWchar &gt;',['../struct_k_g_vector.html',1,'']]],
  ['kgvector_3c_20unsigned_20char_20_3e_288',['KGVector&lt; unsigned char &gt;',['../struct_k_g_vector.html',1,'']]],
  ['kr_5fassert_289',['KR_ASSERT',['../_core_8h.html#aa1ec71e8b97d939f75e13db3a94b5409',1,'Core.h']]],
  ['kr_5fbind_5fevent_5ffn_290',['KR_BIND_EVENT_FN',['../_core_8h.html#a32ecba5b2ab37e1478d0fdfe3799ee1c',1,'Core.h']]],
  ['kr_5fcore_5ferror_291',['KR_CORE_ERROR',['../_log_8h.html#ae1ee8a439091a055d52359b3e4c2c5b4',1,'Log.h']]],
  ['kr_5fcore_5ffatal_292',['KR_CORE_FATAL',['../_log_8h.html#ac83dbc5a47efc56921284077e4f711de',1,'Log.h']]],
  ['kr_5fcore_5finfo_293',['KR_CORE_INFO',['../_log_8h.html#aa7b294e14dcb4b1488d3e87f5bf410a7',1,'Log.h']]],
  ['kr_5fcore_5ftrace_294',['KR_CORE_TRACE',['../_log_8h.html#aefe78a9de92fd065e4c81f6c25d1ae9a',1,'Log.h']]],
  ['kr_5fcore_5fwarn_295',['KR_CORE_WARN',['../_log_8h.html#aa32b050a0e32d8248352ee8c878c2de1',1,'Log.h']]],
  ['kr_5ferror_296',['KR_ERROR',['../_log_8h.html#ab34b15cfb6e5b7c04d17112c60316707',1,'Log.h']]],
  ['kr_5ffatal_297',['KR_FATAL',['../_log_8h.html#a7364ceddebd7acb05eb1c01328370a7a',1,'Log.h']]],
  ['kr_5finfo_298',['KR_INFO',['../_log_8h.html#a0b299bde6f6f2b70720aa07a1383d1cc',1,'Log.h']]],
  ['kr_5fmax_299',['KR_MAX',['../_karma_gui_vulkan_handler_8h.html#a456916e2b388805759c35f0ed74aabd2',1,'KarmaGuiVulkanHandler.h']]],
  ['kr_5fmemalign_300',['KR_MEMALIGN',['../_karma_gui_vulkan_handler_8h.html#af9dbc91d84709fec90b4f29b91cdb5f7',1,'KarmaGuiVulkanHandler.h']]],
  ['kr_5fnoncopyable_301',['KR_NONCOPYABLE',['../_core_8h.html#a0c5af3f446de340dae52d68adf0055df',1,'Core.h']]],
  ['kr_5ftrace_302',['KR_TRACE',['../_log_8h.html#a9a2e0ae0c73f91f2c2d2b4902379e47c',1,'Log.h']]],
  ['kr_5fwarn_303',['KR_WARN',['../_log_8h.html#a34750d29da5f0b16ea59f2122d276ec6',1,'Log.h']]]
];
