var searchData=
[
  ['karma_3a_3aecastcheckedtype_0',['ECastCheckedType',['../namespace_karma_1_1_e_cast_checked_type.html',1,'Karma']]],
  ['karma_5fapi_1',['KARMA_API',['../_core_8h.html#a0362c0681bf67d6dd6b8d2c75866bef4',1,'Core.h']]],
  ['karmaapp_2',['KarmaApp',['../class_karma_app.html',1,'']]],
  ['karmaclassobjectmap_3',['KarmaClassObjectMap',['../class_karma_1_1_karma_class_object_map.html',1,'Karma::KarmaClassObjectMap'],['../class_karma_1_1_karma_class_object_map.html#a89847307c2926edfe4a0273bc0596472',1,'Karma::KarmaClassObjectMap::KarmaClassObjectMap()']]],
  ['karmaengine_4',['KarmaEngine',['../md__r_e_a_d_m_e.html#autotoc_md0',1,'']]],
  ['karmagui_5',['KarmaGui',['../class_karma_1_1_karma_gui.html',1,'Karma']]],
  ['karmagui_2eh_6',['KarmaGui.h',['../_karma_gui_8h.html',1,'']]],
  ['karmagui_5fimplglfw_5fdata_7',['KarmaGui_ImplGlfw_Data',['../struct_karma_gui___impl_glfw___data.html',1,'']]],
  ['karmagui_5fimplglfw_5fviewportdata_8',['KarmaGui_ImplGlfw_ViewportData',['../struct_karma_1_1_karma_gui___impl_glfw___viewport_data.html',1,'Karma']]],
  ['karmagui_5fimplopengl3_5fcreatedeviceobjects_9',['KarmaGui_ImplOpenGL3_CreateDeviceObjects',['../class_karma_1_1_karma_gui_open_g_l_handler.html#a3f307062b620e2af795e39b3fc37f486',1,'Karma::KarmaGuiOpenGLHandler']]],
  ['karmagui_5fimplopengl3_5fcreatefontstexture_10',['KarmaGui_ImplOpenGL3_CreateFontsTexture',['../class_karma_1_1_karma_gui_open_g_l_handler.html#afb5b2473fa343a6965fb971549b5b450',1,'Karma::KarmaGuiOpenGLHandler']]],
  ['karmagui_5fimplopengl3_5fcreatetexture_11',['KarmaGui_ImplOpenGL3_CreateTexture',['../class_karma_1_1_karma_gui_open_g_l_handler.html#a0c3582e02d409c5a73d75c5d99990014',1,'Karma::KarmaGuiOpenGLHandler']]],
  ['karmagui_5fimplopengl3_5fdata_12',['KarmaGui_ImplOpenGL3_Data',['../struct_karma_1_1_karma_gui___impl_open_g_l3___data.html',1,'Karma::KarmaGui_ImplOpenGL3_Data'],['../struct_karma_1_1_karma_gui___impl_open_g_l3___data.html#ae2c1a631c87d335b8e1fb24c04888af6',1,'Karma::KarmaGui_ImplOpenGL3_Data::KarmaGui_ImplOpenGL3_Data()']]],
  ['karmagui_5fimplopengl3_5fdestroydeviceobjects_13',['KarmaGui_ImplOpenGL3_DestroyDeviceObjects',['../class_karma_1_1_karma_gui_open_g_l_handler.html#ad0228fe405121a7ecee245d030455c58',1,'Karma::KarmaGuiOpenGLHandler']]],
  ['karmagui_5fimplopengl3_5fdestroyfontstexture_14',['KarmaGui_ImplOpenGL3_DestroyFontsTexture',['../class_karma_1_1_karma_gui_open_g_l_handler.html#aae7a5b8fb559412fb331525f48f3fbd1',1,'Karma::KarmaGuiOpenGLHandler']]],
  ['karmagui_5fimplopengl3_5finit_15',['KarmaGui_ImplOpenGL3_Init',['../class_karma_1_1_karma_gui_open_g_l_handler.html#a3020e8da89ed6ff2cd26d914f618df82',1,'Karma::KarmaGuiOpenGLHandler']]],
  ['karmagui_5fimplopengl3_5finitplatforminterface_16',['KarmaGui_ImplOpenGL3_InitPlatformInterface',['../class_karma_1_1_karma_gui_open_g_l_handler.html#ad2f705e51d63a8d46c49cbcab9d87acf',1,'Karma::KarmaGuiOpenGLHandler']]],
  ['karmagui_5fimplopengl3_5fnewframe_17',['KarmaGui_ImplOpenGL3_NewFrame',['../class_karma_1_1_karma_gui_open_g_l_handler.html#a9db7d56bf2d2e52c293374786f5581a4',1,'Karma::KarmaGuiOpenGLHandler']]],
  ['karmagui_5fimplopengl3_5frenderdrawdata_18',['KarmaGui_ImplOpenGL3_RenderDrawData',['../class_karma_1_1_karma_gui_open_g_l_handler.html#a4cb6956b66e5abeb43f7c7b8e13a2b84',1,'Karma::KarmaGuiOpenGLHandler']]],
  ['karmagui_5fimplopengl3_5frenderwindow_19',['KarmaGui_ImplOpenGL3_RenderWindow',['../class_karma_1_1_karma_gui_open_g_l_handler.html#a267afab4ed52edf2c7aba250fa0a5cca',1,'Karma::KarmaGuiOpenGLHandler']]],
  ['karmagui_5fimplopengl3_5fsetuprenderstate_20',['KarmaGui_ImplOpenGL3_SetupRenderState',['../class_karma_1_1_karma_gui_open_g_l_handler.html#ae092dd6c4db37e0f995150b2fc9b4370',1,'Karma::KarmaGuiOpenGLHandler']]],
  ['karmagui_5fimplopengl3_5fshutdown_21',['KarmaGui_ImplOpenGL3_Shutdown',['../class_karma_1_1_karma_gui_open_g_l_handler.html#af3bce2e43627ea8affdb7130ac9ee845',1,'Karma::KarmaGuiOpenGLHandler']]],
  ['karmagui_5fimplopengl3_5fshutdownplatforminterface_22',['KarmaGui_ImplOpenGL3_ShutdownPlatformInterface',['../class_karma_1_1_karma_gui_open_g_l_handler.html#a70d4d69bfc1d268274263585327e2e49',1,'Karma::KarmaGuiOpenGLHandler']]],
  ['karmagui_5fimplvulkan_5faddtexture_23',['KarmaGui_ImplVulkan_AddTexture',['../class_karma_1_1_karma_gui_vulkan_handler.html#a69593647c6b97022deb5449e94bdef93',1,'Karma::KarmaGuiVulkanHandler']]],
  ['karmagui_5fimplvulkan_5fcreatedescriptorsetlayout_24',['KarmaGui_ImplVulkan_CreateDescriptorSetLayout',['../class_karma_1_1_karma_gui_vulkan_handler.html#a10ede603ade2ed4ff6d9c093edb53868',1,'Karma::KarmaGuiVulkanHandler']]],
  ['karmagui_5fimplvulkan_5fcreatedeviceobjects_25',['KarmaGui_ImplVulkan_CreateDeviceObjects',['../class_karma_1_1_karma_gui_vulkan_handler.html#a8798f337eabad2a1268cfbaa6114643c',1,'Karma::KarmaGuiVulkanHandler']]],
  ['karmagui_5fimplvulkan_5fcreatefontsampler_26',['KarmaGui_ImplVulkan_CreateFontSampler',['../class_karma_1_1_karma_gui_vulkan_handler.html#aa583f5e1a61b93581443dc2382056da6',1,'Karma::KarmaGuiVulkanHandler']]],
  ['karmagui_5fimplvulkan_5fcreatefontstexture_27',['KarmaGui_ImplVulkan_CreateFontsTexture',['../class_karma_1_1_karma_gui_vulkan_handler.html#a947289d89dbaaaf49ebe72b2a834d9d7',1,'Karma::KarmaGuiVulkanHandler']]],
  ['karmagui_5fimplvulkan_5fcreateorresizewindow_28',['KarmaGui_ImplVulkan_CreateOrResizeWindow',['../class_karma_1_1_karma_gui_vulkan_handler.html#aee8565ba0b84ee6611092898b9a94d2d',1,'Karma::KarmaGuiVulkanHandler']]],
  ['karmagui_5fimplvulkan_5fcreatepipeline_29',['KarmaGui_ImplVulkan_CreatePipeline',['../class_karma_1_1_karma_gui_vulkan_handler.html#aeb43f8c13ca81df044eecbe9dbd05630',1,'Karma::KarmaGuiVulkanHandler']]],
  ['karmagui_5fimplvulkan_5fcreatepipelinelayout_30',['KarmaGui_ImplVulkan_CreatePipelineLayout',['../class_karma_1_1_karma_gui_vulkan_handler.html#ab0b7ac4443496f979c1532a8bd4a1a72',1,'Karma::KarmaGuiVulkanHandler']]],
  ['karmagui_5fimplvulkan_5fcreateshadermodules_31',['KarmaGui_ImplVulkan_CreateShaderModules',['../class_karma_1_1_karma_gui_vulkan_handler.html#abd34e93e2175ac37b4c01191aa77298b',1,'Karma::KarmaGuiVulkanHandler']]],
  ['karmagui_5fimplvulkan_5fcreatetexture_32',['KarmaGui_ImplVulkan_CreateTexture',['../class_karma_1_1_karma_gui_vulkan_handler.html#a218401e00f91c8083613f52f3b3016fa',1,'Karma::KarmaGuiVulkanHandler']]],
  ['karmagui_5fimplvulkan_5fcreatewindow_33',['KarmaGui_ImplVulkan_CreateWindow',['../class_karma_1_1_karma_gui_vulkan_handler.html#aa6bec71360e2fe60c4cea26dac3cf565',1,'Karma::KarmaGuiVulkanHandler']]],
  ['karmagui_5fimplvulkan_5fdata_34',['KarmaGui_ImplVulkan_Data',['../struct_karma_1_1_karma_gui___impl_vulkan___data.html',1,'Karma']]],
  ['karmagui_5fimplvulkan_5fdestroyallviewportsrenderbuffers_35',['KarmaGui_ImplVulkan_DestroyAllViewportsRenderBuffers',['../class_karma_1_1_karma_gui_vulkan_handler.html#a2601ed7116d9c42c98d5c9c62146fe00',1,'Karma::KarmaGuiVulkanHandler']]],
  ['karmagui_5fimplvulkan_5fdestroydeviceobjects_36',['KarmaGui_ImplVulkan_DestroyDeviceObjects',['../class_karma_1_1_karma_gui_vulkan_handler.html#a1474726a454ef471ef767f903f5551da',1,'Karma::KarmaGuiVulkanHandler']]],
  ['karmagui_5fimplvulkan_5fdestroyfontuploadobjects_37',['KarmaGui_ImplVulkan_DestroyFontUploadObjects',['../class_karma_1_1_karma_gui_vulkan_handler.html#ab0c3277122d232fe6a9bb2f8f8df477a',1,'Karma::KarmaGuiVulkanHandler']]],
  ['karmagui_5fimplvulkan_5fdestroywindow_38',['KarmaGui_ImplVulkan_DestroyWindow',['../class_karma_1_1_karma_gui_vulkan_handler.html#a42881b7018110e014a12ce23d329da65',1,'Karma::KarmaGuiVulkanHandler::KarmaGui_ImplVulkan_DestroyWindow(KarmaGuiViewport *viewport)'],['../class_karma_1_1_karma_gui_vulkan_handler.html#a4ab8fcd5e37558658567a97fc27d9e32',1,'Karma::KarmaGuiVulkanHandler::KarmaGui_ImplVulkan_DestroyWindow(KarmaGui_ImplVulkanH_Window *windowData)']]],
  ['karmagui_5fimplvulkan_5fimage_5ftexturedata_39',['KarmaGui_ImplVulkan_Image_TextureData',['../struct_karma_1_1_karma_gui___impl_vulkan___image___texture_data.html',1,'Karma::KarmaGui_ImplVulkan_Image_TextureData'],['../struct_karma_1_1_karma_gui___impl_vulkan___image___texture_data.html#a3f053b1c33ec10e8ed15e1adafaf8cbc',1,'Karma::KarmaGui_ImplVulkan_Image_TextureData::KarmaGui_ImplVulkan_Image_TextureData()']]],
  ['karmagui_5fimplvulkan_5finit_40',['KarmaGui_ImplVulkan_Init',['../class_karma_1_1_karma_gui_renderer.html#a9b480e660f6873323cbdc9b93c3d2211',1,'Karma::KarmaGuiRenderer']]],
  ['karmagui_5fimplvulkan_5finitinfo_41',['KarmaGui_ImplVulkan_InitInfo',['../struct_karma_1_1_karma_gui___impl_vulkan___init_info.html',1,'Karma']]],
  ['karmagui_5fimplvulkan_5finitplatforminterface_42',['KarmaGui_ImplVulkan_InitPlatformInterface',['../class_karma_1_1_karma_gui_vulkan_handler.html#aedb50322002e6ad8e1eb8e18356adb50',1,'Karma::KarmaGuiVulkanHandler']]],
  ['karmagui_5fimplvulkan_5fmemorytype_43',['KarmaGui_ImplVulkan_MemoryType',['../class_karma_1_1_karma_gui_vulkan_handler.html#a19d9046ecead4192278f5f15dddcca51',1,'Karma::KarmaGuiVulkanHandler']]],
  ['karmagui_5fimplvulkan_5fnewframe_44',['KarmaGui_ImplVulkan_NewFrame',['../class_karma_1_1_karma_gui_vulkan_handler.html#a4ff694292f77f635db29dd1804c13bda',1,'Karma::KarmaGuiVulkanHandler']]],
  ['karmagui_5fimplvulkan_5frenderdrawdata_45',['KarmaGui_ImplVulkan_RenderDrawData',['../class_karma_1_1_karma_gui_vulkan_handler.html#a2ca6554d0fac593aae7be85c39dab4b7',1,'Karma::KarmaGuiVulkanHandler']]],
  ['karmagui_5fimplvulkan_5frenderwindow_46',['KarmaGui_ImplVulkan_RenderWindow',['../class_karma_1_1_karma_gui_vulkan_handler.html#a72b73653d18fdde91d1225e63abf9313',1,'Karma::KarmaGuiVulkanHandler']]],
  ['karmagui_5fimplvulkan_5fsetuprenderstate_47',['KarmaGui_ImplVulkan_SetupRenderState',['../class_karma_1_1_karma_gui_vulkan_handler.html#ac989f0dd29c02b3489ff33a31c0b261b',1,'Karma::KarmaGuiVulkanHandler']]],
  ['karmagui_5fimplvulkan_5fsetuprenderstatefor3drendering_48',['KarmaGui_ImplVulkan_SetupRenderStateFor3DRendering',['../class_karma_1_1_karma_gui_vulkan_handler.html#a09e6fbd79125a5759c82f87aaa7eed33',1,'Karma::KarmaGuiVulkanHandler']]],
  ['karmagui_5fimplvulkan_5fsetwindowsize_49',['KarmaGui_ImplVulkan_SetWindowSize',['../class_karma_1_1_karma_gui_vulkan_handler.html#a2fe945584a8c6cc1b93cce469ea71961',1,'Karma::KarmaGuiVulkanHandler']]],
  ['karmagui_5fimplvulkan_5fshivaframerenderbuffers_50',['KarmaGui_ImplVulkan_ShivaFrameRenderBuffers',['../class_karma_1_1_karma_gui_vulkan_handler.html#a3f0a1ac0b54a0b7ce3896636d75a78c4',1,'Karma::KarmaGuiVulkanHandler']]],
  ['karmagui_5fimplvulkan_5fshivawindowrenderbuffers_51',['KarmaGui_ImplVulkan_ShivaWindowRenderBuffers',['../class_karma_1_1_karma_gui_vulkan_handler.html#af0fcca8d4decb19e46348685131ee6dc',1,'Karma::KarmaGuiVulkanHandler']]],
  ['karmagui_5fimplvulkan_5fshutdown_52',['KarmaGui_ImplVulkan_Shutdown',['../class_karma_1_1_karma_gui_vulkan_handler.html#a4e8f9c6e2dcc1f47adc41ed6f55370d9',1,'Karma::KarmaGuiVulkanHandler']]],
  ['karmagui_5fimplvulkan_5fshutdownplatforminterface_53',['KarmaGui_ImplVulkan_ShutdownPlatformInterface',['../class_karma_1_1_karma_gui_vulkan_handler.html#aef31ff42b26af3f3f9b7b348ca304f42',1,'Karma::KarmaGuiVulkanHandler']]],
  ['karmagui_5fimplvulkan_5fswapbuffers_54',['KarmaGui_ImplVulkan_SwapBuffers',['../class_karma_1_1_karma_gui_vulkan_handler.html#a00a73f7f1e709e8615bff7dc1e5aa00a',1,'Karma::KarmaGuiVulkanHandler']]],
  ['karmagui_5fimplvulkan_5fviewportdata_55',['KarmaGui_ImplVulkan_ViewportData',['../struct_karma_1_1_karma_gui___impl_vulkan___viewport_data.html',1,'Karma::KarmaGui_ImplVulkan_ViewportData'],['../struct_karma_1_1_karma_gui___impl_vulkan___viewport_data.html#a77a729082622d9fbd39839cb50d3f983',1,'Karma::KarmaGui_ImplVulkan_ViewportData::KarmaGui_ImplVulkan_ViewportData()']]],
  ['karmagui_5fimplvulkanh_5fimageframe_56',['KarmaGui_ImplVulkanH_ImageFrame',['../struct_karma_1_1_karma_gui___impl_vulkan_h___image_frame.html',1,'Karma']]],
  ['karmagui_5fimplvulkanh_5fimageframerenderbuffers_57',['KarmaGui_ImplVulkanH_ImageFrameRenderBuffers',['../struct_karma_1_1_karma_gui___impl_vulkan_h___image_frame_render_buffers.html',1,'Karma::KarmaGui_ImplVulkanH_ImageFrameRenderBuffers'],['../struct_karma_1_1_karma_gui___impl_vulkan_h___image_frame_render_buffers.html#a247bf694d13da4e2d260e82cd650092e',1,'Karma::KarmaGui_ImplVulkanH_ImageFrameRenderBuffers::KarmaGui_ImplVulkanH_ImageFrameRenderBuffers()']]],
  ['karmagui_5fimplvulkanh_5fwindow_58',['KarmaGui_ImplVulkanH_Window',['../struct_karma_1_1_karma_gui___impl_vulkan_h___window.html',1,'Karma::KarmaGui_ImplVulkanH_Window'],['../struct_karma_1_1_karma_gui___impl_vulkan_h___window.html#a194b19fa100ff3c1f8399110f43d1346',1,'Karma::KarmaGui_ImplVulkanH_Window::KarmaGui_ImplVulkanH_Window()']]],
  ['karmagui_5fimplvulkanh_5fwindowrenderbuffers_59',['KarmaGui_ImplVulkanH_WindowRenderBuffers',['../struct_karma_1_1_karma_gui___impl_vulkan_h___window_render_buffers.html',1,'Karma']]],
  ['karmagui_5fvulkan_5fframe_5fon_5fflight_60',['KarmaGui_Vulkan_Frame_On_Flight',['../struct_karma_1_1_karma_gui___vulkan___frame___on___flight.html',1,'Karma']]],
  ['karmaguibackendrendereruserdata_61',['KarmaGuiBackendRendererUserData',['../struct_karma_1_1_karma_gui_backend_renderer_user_data.html',1,'Karma']]],
  ['karmaguicontext_62',['KarmaGuiContext',['../struct_karma_gui_context.html',1,'']]],
  ['karmaguidockpreviewdata_63',['KarmaGuiDockPreviewData',['../struct_karma_1_1_karma_gui_dock_preview_data.html',1,'Karma']]],
  ['karmaguiinputtextcallbackdata_64',['KarmaGuiInputTextCallbackData',['../struct_karma_gui_input_text_callback_data.html',1,'']]],
  ['karmaguiinternal_65',['KarmaGuiInternal',['../class_karma_1_1_karma_gui_internal.html',1,'Karma']]],
  ['karmaguiinternal_2eh_66',['KarmaGuiInternal.h',['../_karma_gui_internal_8h.html',1,'']]],
  ['karmaguiio_67',['KarmaGuiIO',['../struct_karma_gui_i_o.html',1,'']]],
  ['karmaguikeydata_68',['KarmaGuiKeyData',['../struct_karma_gui_key_data.html',1,'']]],
  ['karmaguilayer_69',['KarmaGuiLayer',['../class_karma_1_1_karma_gui_layer.html',1,'Karma']]],
  ['karmaguilayer_2eh_70',['KarmaGuiLayer.h',['../_karma_gui_layer_8h.html',1,'']]],
  ['karmaguilistclipper_71',['KarmaGuiListClipper',['../struct_karma_gui_list_clipper.html',1,'']]],
  ['karmaguimesa_72',['KarmaGuiMesa',['../class_karma_1_1_karma_gui_mesa.html',1,'Karma']]],
  ['karmaguimesa_2eh_73',['KarmaGuiMesa.h',['../_karma_gui_mesa_8h.html',1,'']]],
  ['karmaguionceuponaframe_74',['KarmaGuiOnceUponAFrame',['../struct_karma_gui_once_upon_a_frame.html',1,'']]],
  ['karmaguiopenglhandler_75',['KarmaGuiOpenGLHandler',['../class_karma_1_1_karma_gui_open_g_l_handler.html',1,'Karma']]],
  ['karmaguiopenglhandler_2eh_76',['KarmaGuiOpenGLHandler.h',['../_karma_gui_open_g_l_handler_8h.html',1,'']]],
  ['karmaguipayload_77',['KarmaGuiPayload',['../struct_karma_gui_payload.html',1,'']]],
  ['karmaguiplatformimedata_78',['KarmaGuiPlatformImeData',['../struct_karma_gui_platform_ime_data.html',1,'']]],
  ['karmaguiplatformio_79',['KarmaGuiPlatformIO',['../struct_karma_gui_platform_i_o.html',1,'']]],
  ['karmaguiplatformmonitor_80',['KarmaGuiPlatformMonitor',['../struct_karma_gui_platform_monitor.html',1,'']]],
  ['karmaguiplotarraygetterdata_81',['KarmaGuiPlotArrayGetterData',['../struct_karma_gui_plot_array_getter_data.html',1,'']]],
  ['karmaguirender_82',['KarmaGuiRender',['../class_example_layer.html#a5b38153dfdfdd5ab2ff784c70132b471',1,'ExampleLayer::KarmaGuiRender()'],['../class_karma_1_1_karma_gui_layer.html#a80cc8aad61a5ade3541b05557f21edc4',1,'Karma::KarmaGuiLayer::KarmaGuiRender()'],['../class_karma_1_1_layer.html#ab81fb12810d36567ed37af322ef28dea',1,'Karma::Layer::KarmaGuiRender()'],['../class_karma_1_1_editor_layer.html#a3828feabe39100f622d9c255626f8ca0',1,'Karma::EditorLayer::KarmaGuiRender()']]],
  ['karmaguirenderer_83',['KarmaGuiRenderer',['../class_karma_1_1_karma_gui_renderer.html',1,'Karma']]],
  ['karmaguirenderer_2eh_84',['KarmaGuiRenderer.h',['../_karma_gui_renderer_8h.html',1,'']]],
  ['karmaguisizecallbackdata_85',['KarmaGuiSizeCallbackData',['../struct_karma_gui_size_callback_data.html',1,'']]],
  ['karmaguistorage_86',['KarmaGuiStorage',['../struct_karma_gui_storage.html',1,'']]],
  ['karmaguistyle_87',['KarmaGuiStyle',['../struct_karma_gui_style.html',1,'']]],
  ['karmaguitabbarsection_88',['KarmaGuiTabBarSection',['../struct_karma_gui_tab_bar_section.html',1,'']]],
  ['karmaguitablecolumnsortspecs_89',['KarmaGuiTableColumnSortSpecs',['../struct_karma_gui_table_column_sort_specs.html',1,'']]],
  ['karmaguitablesortspecs_90',['KarmaGuiTableSortSpecs',['../struct_karma_gui_table_sort_specs.html',1,'']]],
  ['karmaguitextbuffer_91',['KarmaGuiTextBuffer',['../struct_karma_gui_text_buffer.html',1,'']]],
  ['karmaguitextfilter_92',['KarmaGuiTextFilter',['../struct_karma_gui_text_filter.html',1,'']]],
  ['karmaguiviewport_93',['KarmaGuiViewport',['../struct_karma_gui_viewport.html',1,'']]],
  ['karmaguivulkanhandler_94',['KarmaGuiVulkanHandler',['../class_karma_1_1_karma_gui_vulkan_handler.html',1,'Karma']]],
  ['karmaguivulkanhandler_2eh_95',['KarmaGuiVulkanHandler.h',['../_karma_gui_vulkan_handler_8h.html',1,'']]],
  ['karmaguiwindowclass_96',['KarmaGuiWindowClass',['../struct_karma_gui_window_class.html',1,'']]],
  ['karmalogmesa_97',['KarmaLogMesa',['../struct_karma_1_1_karma_log_mesa.html',1,'Karma']]],
  ['karmamap_98',['KarmaMap',['../class_karma_map.html',1,'KarmaMap&lt; KeyType, ValueType &gt;'],['../class_karma_map.html#ab42fcf49ef01f648342cf924319e9ffe',1,'KarmaMap::KarmaMap()']]],
  ['karmamap_3c_20uclass_20_2a_2c_20karmavector_3c_20uobject_20_2a_20_3e_20_2a_20_3e_99',['KarmaMap&lt; UClass *, KarmaVector&lt; UObject * &gt; * &gt;',['../class_karma_map.html',1,'']]],
  ['karmamath_2eh_100',['KarmaMath.h',['../_karma_math_8h.html',1,'']]],
  ['karmamemory_2eh_101',['KarmaMemory.h',['../_karma_memory_8h.html',1,'']]],
  ['karmasmriti_102',['KarmaSmriti',['../class_karma_1_1_karma_smriti.html',1,'Karma::KarmaSmriti'],['../class_karma_1_1_karma_smriti.html#a3f449d4101020b9a5f79e551e6345ab8',1,'Karma::KarmaSmriti::KarmaSmriti()']]],
  ['karmasmriti_2eh_103',['KarmaSmriti.h',['../_karma_smriti_8h.html',1,'']]],
  ['karmastbtextedit_2eh_104',['KarmaSTBTextEdit.h',['../_karma_s_t_b_text_edit_8h.html',1,'']]],
  ['karmaturingmachineelectronics_105',['KarmaTuringMachineElectronics',['../struct_karma_1_1_karma_turing_machine_electronics.html',1,'Karma']]],
  ['karmatypes_2eh_106',['KarmaTypes.h',['../_karma_types_8h.html',1,'']]],
  ['karmautilities_107',['KarmaUtilities',['../class_karma_1_1_karma_utilities.html',1,'Karma']]],
  ['karmautilities_2eh_108',['KarmaUtilities.h',['../_karma_utilities_8h.html',1,'']]],
  ['karmavector_109',['KarmaVector',['../class_karma_vector.html',1,'KarmaVector&lt; BuildingBlock &gt;'],['../class_karma_vector.html#a2a6f1cd06e52515f0f8b9f5fad083116',1,'KarmaVector::KarmaVector()']]],
  ['karmavector_3c_20fuobjectallocatorcallback_20_3e_110',['KarmaVector&lt; FUObjectAllocatorCallback &gt;',['../class_karma_vector.html',1,'']]],
  ['karmavector_3c_20fuobjectitem_20_2a_20_3e_111',['KarmaVector&lt; FUObjectItem * &gt;',['../class_karma_vector.html',1,'']]],
  ['karmavector_3c_20karma_3a_3aaactor_20_2a_20_3e_112',['KarmaVector&lt; Karma::AActor * &gt;',['../class_karma_vector.html',1,'']]],
  ['karmavector_3c_20karma_3a_3afworldcontext_20_2a_20_3e_113',['KarmaVector&lt; Karma::FWorldContext * &gt;',['../class_karma_vector.html',1,'']]],
  ['karmavector_3c_20karma_3a_3auobject_20_2a_20_3e_114',['KarmaVector&lt; Karma::UObject * &gt;',['../class_karma_vector.html',1,'']]],
  ['karmavector_3c_20karma_3a_3auobjectsstatistics_20_3e_115',['KarmaVector&lt; Karma::UObjectsStatistics &gt;',['../class_karma_vector.html',1,'']]],
  ['karmavector_3c_20karma_3a_3auworld_20_2a_2a_20_3e_116',['KarmaVector&lt; Karma::UWorld ** &gt;',['../class_karma_vector.html',1,'']]],
  ['karmavector_3c_20std_3a_3ashared_5fptr_3c_20karma_3a_3auactorcomponent_20_3e_20_3e_117',['KarmaVector&lt; std::shared_ptr&lt; Karma::UActorComponent &gt; &gt;',['../class_karma_vector.html',1,'']]],
  ['kengine_118',['KEngine',['../class_karma_1_1_k_engine.html',1,'Karma::KEngine'],['../class_karma_1_1_k_engine.html#a2d82337d43a4dea3696b6162a445d512',1,'Karma::KEngine::KEngine()']]],
  ['keyevent_119',['KeyEvent',['../class_karma_1_1_key_event.html',1,'Karma::KeyEvent'],['../class_karma_1_1_key_event.html#aaaa1e581cda1319a62c536f61d858568',1,'Karma::KeyEvent::KeyEvent()']]],
  ['keyevent_2eh_120',['KeyEvent.h',['../_key_event_8h.html',1,'']]],
  ['keypressedevent_121',['KeyPressedEvent',['../class_karma_1_1_key_pressed_event.html',1,'Karma::KeyPressedEvent'],['../class_karma_1_1_key_pressed_event.html#a8b3881e519f1d2c0df050da3e7cd30fa',1,'Karma::KeyPressedEvent::KeyPressedEvent()']]],
  ['keyreleasedevent_122',['KeyReleasedEvent',['../class_karma_1_1_key_released_event.html',1,'Karma::KeyReleasedEvent'],['../class_karma_1_1_key_released_event.html#a1c599f02084537537bfde34cc2fce593',1,'Karma::KeyReleasedEvent::KeyReleasedEvent()']]],
  ['keytypedevent_123',['KeyTypedEvent',['../class_karma_1_1_key_typed_event.html',1,'Karma::KeyTypedEvent'],['../class_karma_1_1_key_typed_event.html#a28e7528d39c101e08f3d5e7874997553',1,'Karma::KeyTypedEvent::KeyTypedEvent()']]],
  ['kgbitarray_124',['KGBitArray',['../struct_k_g_bit_array.html',1,'']]],
  ['kgbitarray_3c_20kgguikey_5fnamedkey_5fcount_2c_20_2dkgguikey_5fnamedkey_5fbegin_20_3e_125',['KGBitArray&lt; KGGuiKey_NamedKey_COUNT, -KGGuiKey_NamedKey_BEGIN &gt;',['../struct_k_g_bit_array.html',1,'']]],
  ['kgbitvector_126',['KGBitVector',['../struct_k_g_bit_vector.html',1,'']]],
  ['kgchunkstream_127',['KGChunkStream',['../struct_k_g_chunk_stream.html',1,'']]],
  ['kgchunkstream_3c_20kgguitablesettings_20_3e_128',['KGChunkStream&lt; KGGuiTableSettings &gt;',['../struct_k_g_chunk_stream.html',1,'']]],
  ['kgchunkstream_3c_20kgguiwindowsettings_20_3e_129',['KGChunkStream&lt; KGGuiWindowSettings &gt;',['../struct_k_g_chunk_stream.html',1,'']]],
  ['kgcolor_130',['KGColor',['../struct_k_g_color.html',1,'']]],
  ['kgdrawchannel_131',['KGDrawChannel',['../struct_k_g_draw_channel.html',1,'']]],
  ['kgdrawcmd_132',['KGDrawCmd',['../struct_k_g_draw_cmd.html',1,'']]],
  ['kgdrawdata_133',['KGDrawData',['../struct_k_g_draw_data.html',1,'']]],
  ['kgdrawdatabuilder_134',['KGDrawDataBuilder',['../struct_k_g_draw_data_builder.html',1,'']]],
  ['kgdrawlist_135',['KGDrawList',['../struct_k_g_draw_list.html',1,'']]],
  ['kgdrawlistshareddata_136',['KGDrawListSharedData',['../struct_k_g_draw_list_shared_data.html',1,'']]],
  ['kgdrawlistsplitter_137',['KGDrawListSplitter',['../struct_k_g_draw_list_splitter.html',1,'']]],
  ['kgdrawvert_138',['KGDrawVert',['../struct_k_g_draw_vert.html',1,'']]],
  ['kgfont_139',['KGFont',['../struct_k_g_font.html',1,'']]],
  ['kgfontatlas_140',['KGFontAtlas',['../struct_k_g_font_atlas.html',1,'']]],
  ['kgfontatlascustomrect_141',['KGFontAtlasCustomRect',['../struct_k_g_font_atlas_custom_rect.html',1,'']]],
  ['kgfontbuilddstdata_142',['KGFontBuildDstData',['../struct_k_g_font_build_dst_data.html',1,'']]],
  ['kgfontbuilderio_143',['KGFontBuilderIO',['../struct_k_g_font_builder_i_o.html',1,'']]],
  ['kgfontbuildsrcdata_144',['KGFontBuildSrcData',['../struct_k_g_font_build_src_data.html',1,'']]],
  ['kgfontconfig_145',['KGFontConfig',['../struct_k_g_font_config.html',1,'']]],
  ['kgfontglyph_146',['KGFontGlyph',['../struct_k_g_font_glyph.html',1,'']]],
  ['kgfontglyphrangesbuilder_147',['KGFontGlyphRangesBuilder',['../struct_k_g_font_glyph_ranges_builder.html',1,'']]],
  ['kgguicolormod_148',['KGGuiColorMod',['../struct_k_g_gui_color_mod.html',1,'']]],
  ['kgguicombopreviewdata_149',['KGGuiComboPreviewData',['../struct_k_g_gui_combo_preview_data.html',1,'']]],
  ['kgguicontexthook_150',['KGGuiContextHook',['../struct_k_g_gui_context_hook.html',1,'']]],
  ['kgguidatatypeinfo_151',['KGGuiDataTypeInfo',['../struct_k_g_gui_data_type_info.html',1,'']]],
  ['kgguidatatypetempstorage_152',['KGGuiDataTypeTempStorage',['../struct_k_g_gui_data_type_temp_storage.html',1,'']]],
  ['kgguidockcontext_153',['KGGuiDockContext',['../struct_k_g_gui_dock_context.html',1,'']]],
  ['kgguidocknode_154',['KGGuiDockNode',['../struct_k_g_gui_dock_node.html',1,'']]],
  ['kgguidocknodesettings_155',['KGGuiDockNodeSettings',['../struct_k_g_gui_dock_node_settings.html',1,'']]],
  ['kgguidockrequest_156',['KGGuiDockRequest',['../struct_k_g_gui_dock_request.html',1,'']]],
  ['kgguigroupdata_157',['KGGuiGroupData',['../struct_k_g_gui_group_data.html',1,'']]],
  ['kgguiinputevent_158',['KGGuiInputEvent',['../struct_k_g_gui_input_event.html',1,'']]],
  ['kgguiinputeventappfocused_159',['KGGuiInputEventAppFocused',['../struct_k_g_gui_input_event_app_focused.html',1,'']]],
  ['kgguiinputeventkey_160',['KGGuiInputEventKey',['../struct_k_g_gui_input_event_key.html',1,'']]],
  ['kgguiinputeventmousebutton_161',['KGGuiInputEventMouseButton',['../struct_k_g_gui_input_event_mouse_button.html',1,'']]],
  ['kgguiinputeventmousepos_162',['KGGuiInputEventMousePos',['../struct_k_g_gui_input_event_mouse_pos.html',1,'']]],
  ['kgguiinputeventmouseviewport_163',['KGGuiInputEventMouseViewport',['../struct_k_g_gui_input_event_mouse_viewport.html',1,'']]],
  ['kgguiinputeventmousewheel_164',['KGGuiInputEventMouseWheel',['../struct_k_g_gui_input_event_mouse_wheel.html',1,'']]],
  ['kgguiinputeventtext_165',['KGGuiInputEventText',['../struct_k_g_gui_input_event_text.html',1,'']]],
  ['kgguiinputtextstate_166',['KGGuiInputTextState',['../struct_k_g_gui_input_text_state.html',1,'']]],
  ['kgguikeyownerdata_167',['KGGuiKeyOwnerData',['../struct_k_g_gui_key_owner_data.html',1,'']]],
  ['kgguikeyroutingdata_168',['KGGuiKeyRoutingData',['../struct_k_g_gui_key_routing_data.html',1,'']]],
  ['kgguikeyroutingtable_169',['KGGuiKeyRoutingTable',['../struct_k_g_gui_key_routing_table.html',1,'']]],
  ['kgguilastitemdata_170',['KGGuiLastItemData',['../struct_k_g_gui_last_item_data.html',1,'']]],
  ['kgguilistclipperdata_171',['KGGuiListClipperData',['../struct_k_g_gui_list_clipper_data.html',1,'']]],
  ['kgguilistclipperrange_172',['KGGuiListClipperRange',['../struct_k_g_gui_list_clipper_range.html',1,'']]],
  ['kgguilocentry_173',['KGGuiLocEntry',['../struct_k_g_gui_loc_entry.html',1,'']]],
  ['kgguimenucolumns_174',['KGGuiMenuColumns',['../struct_k_g_gui_menu_columns.html',1,'']]],
  ['kgguimetricsconfig_175',['KGGuiMetricsConfig',['../struct_k_g_gui_metrics_config.html',1,'']]],
  ['kgguinavitemdata_176',['KGGuiNavItemData',['../struct_k_g_gui_nav_item_data.html',1,'']]],
  ['kgguinextitemdata_177',['KGGuiNextItemData',['../struct_k_g_gui_next_item_data.html',1,'']]],
  ['kgguinextwindowdata_178',['KGGuiNextWindowData',['../struct_k_g_gui_next_window_data.html',1,'']]],
  ['kgguioldcolumndata_179',['KGGuiOldColumnData',['../struct_k_g_gui_old_column_data.html',1,'']]],
  ['kgguioldcolumns_180',['KGGuiOldColumns',['../struct_k_g_gui_old_columns.html',1,'']]],
  ['kgguipopupdata_181',['KGGuiPopupData',['../struct_k_g_gui_popup_data.html',1,'']]],
  ['kgguiptrorindex_182',['KGGuiPtrOrIndex',['../struct_k_g_gui_ptr_or_index.html',1,'']]],
  ['kgguisettingshandler_183',['KGGuiSettingsHandler',['../struct_k_g_gui_settings_handler.html',1,'']]],
  ['kgguishrinkwidthitem_184',['KGGuiShrinkWidthItem',['../struct_k_g_gui_shrink_width_item.html',1,'']]],
  ['kgguistacklevelinfo_185',['KGGuiStackLevelInfo',['../struct_k_g_gui_stack_level_info.html',1,'']]],
  ['kgguistacksizes_186',['KGGuiStackSizes',['../struct_k_g_gui_stack_sizes.html',1,'']]],
  ['kgguistacktool_187',['KGGuiStackTool',['../struct_k_g_gui_stack_tool.html',1,'']]],
  ['kgguistylemod_188',['KGGuiStyleMod',['../struct_k_g_gui_style_mod.html',1,'']]],
  ['kgguitabbar_189',['KGGuiTabBar',['../struct_k_g_gui_tab_bar.html',1,'']]],
  ['kgguitabitem_190',['KGGuiTabItem',['../struct_k_g_gui_tab_item.html',1,'']]],
  ['kgguitable_191',['KGGuiTable',['../struct_k_g_gui_table.html',1,'']]],
  ['kgguitablecelldata_192',['KGGuiTableCellData',['../struct_k_g_gui_table_cell_data.html',1,'']]],
  ['kgguitablecolumn_193',['KGGuiTableColumn',['../struct_k_g_gui_table_column.html',1,'']]],
  ['kgguitablecolumnsettings_194',['KGGuiTableColumnSettings',['../struct_k_g_gui_table_column_settings.html',1,'']]],
  ['kgguitableinstancedata_195',['KGGuiTableInstanceData',['../struct_k_g_gui_table_instance_data.html',1,'']]],
  ['kgguitablesettings_196',['KGGuiTableSettings',['../struct_k_g_gui_table_settings.html',1,'']]],
  ['kgguitabletempdata_197',['KGGuiTableTempData',['../struct_k_g_gui_table_temp_data.html',1,'']]],
  ['kgguitextindex_198',['KGGuiTextIndex',['../struct_k_g_gui_text_index.html',1,'']]],
  ['kgguiviewportp_199',['KGGuiViewportP',['../struct_k_g_gui_viewport_p.html',1,'']]],
  ['kgguiwindow_200',['KGGuiWindow',['../struct_k_g_gui_window.html',1,'']]],
  ['kgguiwindowdockstyle_201',['KGGuiWindowDockStyle',['../struct_k_g_gui_window_dock_style.html',1,'']]],
  ['kgguiwindowsettings_202',['KGGuiWindowSettings',['../struct_k_g_gui_window_settings.html',1,'']]],
  ['kgguiwindowstackdata_203',['KGGuiWindowStackData',['../struct_k_g_gui_window_stack_data.html',1,'']]],
  ['kgguiwindowtempdata_204',['KGGuiWindowTempData',['../struct_k_g_gui_window_temp_data.html',1,'']]],
  ['kgnewwrapper_205',['KGNewWrapper',['../struct_k_g_new_wrapper.html',1,'']]],
  ['kgpool_206',['KGPool',['../struct_k_g_pool.html',1,'']]],
  ['kgpool_3c_20kgguitabbar_20_3e_207',['KGPool&lt; KGGuiTabBar &gt;',['../struct_k_g_pool.html',1,'']]],
  ['kgpool_3c_20kgguitable_20_3e_208',['KGPool&lt; KGGuiTable &gt;',['../struct_k_g_pool.html',1,'']]],
  ['kgrect_209',['KGRect',['../struct_k_g_rect.html',1,'']]],
  ['kgspan_210',['KGSpan',['../struct_k_g_span.html',1,'']]],
  ['kgspan_3c_20kgguitablecelldata_20_3e_211',['KGSpan&lt; KGGuiTableCellData &gt;',['../struct_k_g_span.html',1,'']]],
  ['kgspan_3c_20kgguitablecolumn_20_3e_212',['KGSpan&lt; KGGuiTableColumn &gt;',['../struct_k_g_span.html',1,'']]],
  ['kgspan_3c_20kgguitablecolumnidx_20_3e_213',['KGSpan&lt; KGGuiTableColumnIdx &gt;',['../struct_k_g_span.html',1,'']]],
  ['kgspanallocator_214',['KGSpanAllocator',['../struct_k_g_span_allocator.html',1,'']]],
  ['kgvec1_215',['KGVec1',['../struct_k_g_vec1.html',1,'']]],
  ['kgvec2_216',['KGVec2',['../struct_k_g_vec2.html',1,'']]],
  ['kgvec2ih_217',['KGVec2ih',['../struct_k_g_vec2ih.html',1,'']]],
  ['kgvec4_218',['KGVec4',['../struct_k_g_vec4.html',1,'']]],
  ['kgvector_219',['KGVector',['../struct_k_g_vector.html',1,'']]],
  ['kgvector_3c_20char_20_3e_220',['KGVector&lt; char &gt;',['../struct_k_g_vector.html',1,'']]],
  ['kgvector_3c_20float_20_3e_221',['KGVector&lt; float &gt;',['../struct_k_g_vector.html',1,'']]],
  ['kgvector_3c_20int_20_3e_222',['KGVector&lt; int &gt;',['../struct_k_g_vector.html',1,'']]],
  ['kgvector_3c_20karmaguiplatformmonitor_20_3e_223',['KGVector&lt; KarmaGuiPlatformMonitor &gt;',['../struct_k_g_vector.html',1,'']]],
  ['kgvector_3c_20karmaguistorage_3a_3aimguistoragepair_20_3e_224',['KGVector&lt; KarmaGuiStorage::ImGuiStoragePair &gt;',['../struct_k_g_vector.html',1,'']]],
  ['kgvector_3c_20karmaguitablecolumnsortspecs_20_3e_225',['KGVector&lt; KarmaGuiTableColumnSortSpecs &gt;',['../struct_k_g_vector.html',1,'']]],
  ['kgvector_3c_20karmaguitextfilter_3a_3aimguitextrange_20_3e_226',['KGVector&lt; KarmaGuiTextFilter::ImGuiTextRange &gt;',['../struct_k_g_vector.html',1,'']]],
  ['kgvector_3c_20karmaguiviewport_20_2a_20_3e_227',['KGVector&lt; KarmaGuiViewport * &gt;',['../struct_k_g_vector.html',1,'']]],
  ['kgvector_3c_20kgdrawchannel_20_3e_228',['KGVector&lt; KGDrawChannel &gt;',['../struct_k_g_vector.html',1,'']]],
  ['kgvector_3c_20kgdrawcmd_20_3e_229',['KGVector&lt; KGDrawCmd &gt;',['../struct_k_g_vector.html',1,'']]],
  ['kgvector_3c_20kgdrawidx_20_3e_230',['KGVector&lt; KGDrawIdx &gt;',['../struct_k_g_vector.html',1,'']]],
  ['kgvector_3c_20kgdrawlist_20_2a_20_3e_231',['KGVector&lt; KGDrawList * &gt;',['../struct_k_g_vector.html',1,'']]],
  ['kgvector_3c_20kgdrawvert_20_3e_232',['KGVector&lt; KGDrawVert &gt;',['../struct_k_g_vector.html',1,'']]],
  ['kgvector_3c_20kgfont_20_2a_20_3e_233',['KGVector&lt; KGFont * &gt;',['../struct_k_g_vector.html',1,'']]],
  ['kgvector_3c_20kgfontatlascustomrect_20_3e_234',['KGVector&lt; KGFontAtlasCustomRect &gt;',['../struct_k_g_vector.html',1,'']]],
  ['kgvector_3c_20kgfontconfig_20_3e_235',['KGVector&lt; KGFontConfig &gt;',['../struct_k_g_vector.html',1,'']]],
  ['kgvector_3c_20kgfontglyph_20_3e_236',['KGVector&lt; KGFontGlyph &gt;',['../struct_k_g_vector.html',1,'']]],
  ['kgvector_3c_20kgguicolormod_20_3e_237',['KGVector&lt; KGGuiColorMod &gt;',['../struct_k_g_vector.html',1,'']]],
  ['kgvector_3c_20kgguicontexthook_20_3e_238',['KGVector&lt; KGGuiContextHook &gt;',['../struct_k_g_vector.html',1,'']]],
  ['kgvector_3c_20kgguidocknodesettings_20_3e_239',['KGVector&lt; KGGuiDockNodeSettings &gt;',['../struct_k_g_vector.html',1,'']]],
  ['kgvector_3c_20kgguidockrequest_20_3e_240',['KGVector&lt; KGGuiDockRequest &gt;',['../struct_k_g_vector.html',1,'']]],
  ['kgvector_3c_20kgguigroupdata_20_3e_241',['KGVector&lt; KGGuiGroupData &gt;',['../struct_k_g_vector.html',1,'']]],
  ['kgvector_3c_20kgguiid_20_3e_242',['KGVector&lt; KGGuiID &gt;',['../struct_k_g_vector.html',1,'']]],
  ['kgvector_3c_20kgguiinputevent_20_3e_243',['KGVector&lt; KGGuiInputEvent &gt;',['../struct_k_g_vector.html',1,'']]],
  ['kgvector_3c_20kgguiitemflags_20_3e_244',['KGVector&lt; KGGuiItemFlags &gt;',['../struct_k_g_vector.html',1,'']]],
  ['kgvector_3c_20kgguikeyroutingdata_20_3e_245',['KGVector&lt; KGGuiKeyRoutingData &gt;',['../struct_k_g_vector.html',1,'']]],
  ['kgvector_3c_20kgguilistclipperdata_20_3e_246',['KGVector&lt; KGGuiListClipperData &gt;',['../struct_k_g_vector.html',1,'']]],
  ['kgvector_3c_20kgguilistclipperrange_20_3e_247',['KGVector&lt; KGGuiListClipperRange &gt;',['../struct_k_g_vector.html',1,'']]],
  ['kgvector_3c_20kgguioldcolumndata_20_3e_248',['KGVector&lt; KGGuiOldColumnData &gt;',['../struct_k_g_vector.html',1,'']]],
  ['kgvector_3c_20kgguioldcolumns_20_3e_249',['KGVector&lt; KGGuiOldColumns &gt;',['../struct_k_g_vector.html',1,'']]],
  ['kgvector_3c_20kgguipopupdata_20_3e_250',['KGVector&lt; KGGuiPopupData &gt;',['../struct_k_g_vector.html',1,'']]],
  ['kgvector_3c_20kgguiptrorindex_20_3e_251',['KGVector&lt; KGGuiPtrOrIndex &gt;',['../struct_k_g_vector.html',1,'']]],
  ['kgvector_3c_20kgguisettingshandler_20_3e_252',['KGVector&lt; KGGuiSettingsHandler &gt;',['../struct_k_g_vector.html',1,'']]],
  ['kgvector_3c_20kgguishrinkwidthitem_20_3e_253',['KGVector&lt; KGGuiShrinkWidthItem &gt;',['../struct_k_g_vector.html',1,'']]],
  ['kgvector_3c_20kgguistacklevelinfo_20_3e_254',['KGVector&lt; KGGuiStackLevelInfo &gt;',['../struct_k_g_vector.html',1,'']]],
  ['kgvector_3c_20kgguistylemod_20_3e_255',['KGVector&lt; KGGuiStyleMod &gt;',['../struct_k_g_vector.html',1,'']]],
  ['kgvector_3c_20kgguitabbar_20_3e_256',['KGVector&lt; KGGuiTabBar &gt;',['../struct_k_g_vector.html',1,'']]],
  ['kgvector_3c_20kgguitabitem_20_3e_257',['KGVector&lt; KGGuiTabItem &gt;',['../struct_k_g_vector.html',1,'']]],
  ['kgvector_3c_20kgguitable_20_3e_258',['KGVector&lt; KGGuiTable &gt;',['../struct_k_g_vector.html',1,'']]],
  ['kgvector_3c_20kgguitableinstancedata_20_3e_259',['KGVector&lt; KGGuiTableInstanceData &gt;',['../struct_k_g_vector.html',1,'']]],
  ['kgvector_3c_20kgguitabletempdata_20_3e_260',['KGVector&lt; KGGuiTableTempData &gt;',['../struct_k_g_vector.html',1,'']]],
  ['kgvector_3c_20kgguiviewportp_20_2a_20_3e_261',['KGVector&lt; KGGuiViewportP * &gt;',['../struct_k_g_vector.html',1,'']]],
  ['kgvector_3c_20kgguiwindow_20_2a_20_3e_262',['KGVector&lt; KGGuiWindow * &gt;',['../struct_k_g_vector.html',1,'']]],
  ['kgvector_3c_20kgguiwindowstackdata_20_3e_263',['KGVector&lt; KGGuiWindowStackData &gt;',['../struct_k_g_vector.html',1,'']]],
  ['kgvector_3c_20kgtextureid_20_3e_264',['KGVector&lt; KGTextureID &gt;',['../struct_k_g_vector.html',1,'']]],
  ['kgvector_3c_20kgu32_20_3e_265',['KGVector&lt; KGU32 &gt;',['../struct_k_g_vector.html',1,'']]],
  ['kgvector_3c_20kgvec2_20_3e_266',['KGVector&lt; KGVec2 &gt;',['../struct_k_g_vector.html',1,'']]],
  ['kgvector_3c_20kgvec4_20_3e_267',['KGVector&lt; KGVec4 &gt;',['../struct_k_g_vector.html',1,'']]],
  ['kgvector_3c_20kgwchar_20_3e_268',['KGVector&lt; KGWchar &gt;',['../struct_k_g_vector.html',1,'']]],
  ['kgvector_3c_20unsigned_20char_20_3e_269',['KGVector&lt; unsigned char &gt;',['../struct_k_g_vector.html',1,'']]],
  ['kr_5fassert_270',['KR_ASSERT',['../_core_8h.html#aa1ec71e8b97d939f75e13db3a94b5409',1,'Core.h']]],
  ['kr_5fbind_5fevent_5ffn_271',['KR_BIND_EVENT_FN',['../_core_8h.html#a32ecba5b2ab37e1478d0fdfe3799ee1c',1,'Core.h']]],
  ['kr_5fcore_5ferror_272',['KR_CORE_ERROR',['../_log_8h.html#ae1ee8a439091a055d52359b3e4c2c5b4',1,'Log.h']]],
  ['kr_5fcore_5ffatal_273',['KR_CORE_FATAL',['../_log_8h.html#ac83dbc5a47efc56921284077e4f711de',1,'Log.h']]],
  ['kr_5fcore_5finfo_274',['KR_CORE_INFO',['../_log_8h.html#aa7b294e14dcb4b1488d3e87f5bf410a7',1,'Log.h']]],
  ['kr_5fcore_5ftrace_275',['KR_CORE_TRACE',['../_log_8h.html#aefe78a9de92fd065e4c81f6c25d1ae9a',1,'Log.h']]],
  ['kr_5fcore_5fwarn_276',['KR_CORE_WARN',['../_log_8h.html#aa32b050a0e32d8248352ee8c878c2de1',1,'Log.h']]],
  ['kr_5ferror_277',['KR_ERROR',['../_log_8h.html#ab34b15cfb6e5b7c04d17112c60316707',1,'Log.h']]],
  ['kr_5ffatal_278',['KR_FATAL',['../_log_8h.html#a7364ceddebd7acb05eb1c01328370a7a',1,'Log.h']]],
  ['kr_5finfo_279',['KR_INFO',['../_log_8h.html#a0b299bde6f6f2b70720aa07a1383d1cc',1,'Log.h']]],
  ['kr_5fmax_280',['KR_MAX',['../_karma_gui_vulkan_handler_8h.html#a456916e2b388805759c35f0ed74aabd2',1,'KarmaGuiVulkanHandler.h']]],
  ['kr_5fmemalign_281',['KR_MEMALIGN',['../_karma_gui_vulkan_handler_8h.html#af9dbc91d84709fec90b4f29b91cdb5f7',1,'KarmaGuiVulkanHandler.h']]],
  ['kr_5fnoncopyable_282',['KR_NONCOPYABLE',['../_core_8h.html#a0c5af3f446de340dae52d68adf0055df',1,'Core.h']]],
  ['kr_5ftrace_283',['KR_TRACE',['../_log_8h.html#a9a2e0ae0c73f91f2c2d2b4902379e47c',1,'Log.h']]],
  ['kr_5fwarn_284',['KR_WARN',['../_log_8h.html#a34750d29da5f0b16ea59f2122d276ec6',1,'Log.h']]]
];
