var searchData=
[
  ['karmaapp_0',['KarmaApp',['../classKarmaApp.html',1,'']]],
  ['karmagui_1',['KarmaGui',['../classKarma_1_1KarmaGui.html',1,'Karma']]],
  ['karmaguicontext_2',['KarmaGuiContext',['../structKarmaGuiContext.html',1,'']]],
  ['karmaguiinputtextcallbackdata_3',['KarmaGuiInputTextCallbackData',['../structKarmaGuiInputTextCallbackData.html',1,'']]],
  ['karmaguiinternal_4',['KarmaGuiInternal',['../classKarma_1_1KarmaGuiInternal.html',1,'Karma']]],
  ['karmaguiio_5',['KarmaGuiIO',['../structKarmaGuiIO.html',1,'']]],
  ['karmaguikeydata_6',['KarmaGuiKeyData',['../structKarmaGuiKeyData.html',1,'']]],
  ['karmaguilistclipper_7',['KarmaGuiListClipper',['../structKarmaGuiListClipper.html',1,'']]],
  ['karmaguionceuponaframe_8',['KarmaGuiOnceUponAFrame',['../structKarmaGuiOnceUponAFrame.html',1,'']]],
  ['karmaguipayload_9',['KarmaGuiPayload',['../structKarmaGuiPayload.html',1,'']]],
  ['karmaguiplatformimedata_10',['KarmaGuiPlatformImeData',['../structKarmaGuiPlatformImeData.html',1,'']]],
  ['karmaguiplatformio_11',['KarmaGuiPlatformIO',['../structKarmaGuiPlatformIO.html',1,'']]],
  ['karmaguiplatformmonitor_12',['KarmaGuiPlatformMonitor',['../structKarmaGuiPlatformMonitor.html',1,'']]],
  ['karmaguisizecallbackdata_13',['KarmaGuiSizeCallbackData',['../structKarmaGuiSizeCallbackData.html',1,'']]],
  ['karmaguistorage_14',['KarmaGuiStorage',['../structKarmaGuiStorage.html',1,'']]],
  ['karmaguistyle_15',['KarmaGuiStyle',['../structKarmaGuiStyle.html',1,'']]],
  ['karmaguitablecolumnsortspecs_16',['KarmaGuiTableColumnSortSpecs',['../structKarmaGuiTableColumnSortSpecs.html',1,'']]],
  ['karmaguitablesortspecs_17',['KarmaGuiTableSortSpecs',['../structKarmaGuiTableSortSpecs.html',1,'']]],
  ['karmaguitextbuffer_18',['KarmaGuiTextBuffer',['../structKarmaGuiTextBuffer.html',1,'']]],
  ['karmaguitextfilter_19',['KarmaGuiTextFilter',['../structKarmaGuiTextFilter.html',1,'']]],
  ['karmaguiviewport_20',['KarmaGuiViewport',['../structKarmaGuiViewport.html',1,'']]],
  ['karmaguiwindowclass_21',['KarmaGuiWindowClass',['../structKarmaGuiWindowClass.html',1,'']]],
  ['karmalogmesa_22',['KarmaLogMesa',['../structKarma_1_1KarmaLogMesa.html',1,'Karma']]],
  ['karmaturingmachineelectronics_23',['KarmaTuringMachineElectronics',['../structKarma_1_1KarmaTuringMachineElectronics.html',1,'Karma']]],
  ['karmautilities_24',['KarmaUtilities',['../classKarma_1_1KarmaUtilities.html',1,'Karma']]],
  ['keyevent_25',['KeyEvent',['../classKarma_1_1KeyEvent.html',1,'Karma']]],
  ['keypressedevent_26',['KeyPressedEvent',['../classKarma_1_1KeyPressedEvent.html',1,'Karma']]],
  ['keyreleasedevent_27',['KeyReleasedEvent',['../classKarma_1_1KeyReleasedEvent.html',1,'Karma']]],
  ['keytypedevent_28',['KeyTypedEvent',['../classKarma_1_1KeyTypedEvent.html',1,'Karma']]],
  ['kgbitarray_29',['KGBitArray',['../structKGBitArray.html',1,'']]],
  ['kgbitvector_30',['KGBitVector',['../structKGBitVector.html',1,'']]],
  ['kgchunkstream_31',['KGChunkStream',['../structKGChunkStream.html',1,'']]],
  ['kgchunkstream_3c_20kgguitablesettings_20_3e_32',['KGChunkStream&lt; KGGuiTableSettings &gt;',['../structKGChunkStream.html',1,'']]],
  ['kgchunkstream_3c_20kgguiwindowsettings_20_3e_33',['KGChunkStream&lt; KGGuiWindowSettings &gt;',['../structKGChunkStream.html',1,'']]],
  ['kgcolor_34',['KGColor',['../structKGColor.html',1,'']]],
  ['kgdrawchannel_35',['KGDrawChannel',['../structKGDrawChannel.html',1,'']]],
  ['kgdrawcmd_36',['KGDrawCmd',['../structKGDrawCmd.html',1,'']]],
  ['kgdrawdata_37',['KGDrawData',['../structKGDrawData.html',1,'']]],
  ['kgdrawdatabuilder_38',['KGDrawDataBuilder',['../structKGDrawDataBuilder.html',1,'']]],
  ['kgdrawlist_39',['KGDrawList',['../structKGDrawList.html',1,'']]],
  ['kgdrawlistshareddata_40',['KGDrawListSharedData',['../structKGDrawListSharedData.html',1,'']]],
  ['kgdrawlistsplitter_41',['KGDrawListSplitter',['../structKGDrawListSplitter.html',1,'']]],
  ['kgdrawvert_42',['KGDrawVert',['../structKGDrawVert.html',1,'']]],
  ['kgfont_43',['KGFont',['../structKGFont.html',1,'']]],
  ['kgfontatlas_44',['KGFontAtlas',['../structKGFontAtlas.html',1,'']]],
  ['kgfontatlascustomrect_45',['KGFontAtlasCustomRect',['../structKGFontAtlasCustomRect.html',1,'']]],
  ['kgfontbuilderio_46',['KGFontBuilderIO',['../structKGFontBuilderIO.html',1,'']]],
  ['kgfontconfig_47',['KGFontConfig',['../structKGFontConfig.html',1,'']]],
  ['kgfontglyph_48',['KGFontGlyph',['../structKGFontGlyph.html',1,'']]],
  ['kgfontglyphrangesbuilder_49',['KGFontGlyphRangesBuilder',['../structKGFontGlyphRangesBuilder.html',1,'']]],
  ['kgguicolormod_50',['KGGuiColorMod',['../structKGGuiColorMod.html',1,'']]],
  ['kgguicombopreviewdata_51',['KGGuiComboPreviewData',['../structKGGuiComboPreviewData.html',1,'']]],
  ['kgguicontexthook_52',['KGGuiContextHook',['../structKGGuiContextHook.html',1,'']]],
  ['kgguidatatypeinfo_53',['KGGuiDataTypeInfo',['../structKGGuiDataTypeInfo.html',1,'']]],
  ['kgguidatatypetempstorage_54',['KGGuiDataTypeTempStorage',['../structKGGuiDataTypeTempStorage.html',1,'']]],
  ['kgguidocknodesettings_55',['KGGuiDockNodeSettings',['../structKGGuiDockNodeSettings.html',1,'']]],
  ['kgguidockrequest_56',['KGGuiDockRequest',['../structKGGuiDockRequest.html',1,'']]],
  ['kgguigroupdata_57',['KGGuiGroupData',['../structKGGuiGroupData.html',1,'']]],
  ['kgguiinputevent_58',['KGGuiInputEvent',['../structKGGuiInputEvent.html',1,'']]],
  ['kgguiinputeventappfocused_59',['KGGuiInputEventAppFocused',['../structKGGuiInputEventAppFocused.html',1,'']]],
  ['kgguiinputeventkey_60',['KGGuiInputEventKey',['../structKGGuiInputEventKey.html',1,'']]],
  ['kgguiinputeventmousebutton_61',['KGGuiInputEventMouseButton',['../structKGGuiInputEventMouseButton.html',1,'']]],
  ['kgguiinputeventmousepos_62',['KGGuiInputEventMousePos',['../structKGGuiInputEventMousePos.html',1,'']]],
  ['kgguiinputeventmouseviewport_63',['KGGuiInputEventMouseViewport',['../structKGGuiInputEventMouseViewport.html',1,'']]],
  ['kgguiinputeventmousewheel_64',['KGGuiInputEventMouseWheel',['../structKGGuiInputEventMouseWheel.html',1,'']]],
  ['kgguiinputeventtext_65',['KGGuiInputEventText',['../structKGGuiInputEventText.html',1,'']]],
  ['kgguiinputtextstate_66',['KGGuiInputTextState',['../structKGGuiInputTextState.html',1,'']]],
  ['kgguikeyownerdata_67',['KGGuiKeyOwnerData',['../structKGGuiKeyOwnerData.html',1,'']]],
  ['kgguikeyroutingdata_68',['KGGuiKeyRoutingData',['../structKGGuiKeyRoutingData.html',1,'']]],
  ['kgguikeyroutingtable_69',['KGGuiKeyRoutingTable',['../structKGGuiKeyRoutingTable.html',1,'']]],
  ['kgguilastitemdata_70',['KGGuiLastItemData',['../structKGGuiLastItemData.html',1,'']]],
  ['kgguilistclipperdata_71',['KGGuiListClipperData',['../structKGGuiListClipperData.html',1,'']]],
  ['kgguilistclipperrange_72',['KGGuiListClipperRange',['../structKGGuiListClipperRange.html',1,'']]],
  ['kgguilocentry_73',['KGGuiLocEntry',['../structKGGuiLocEntry.html',1,'']]],
  ['kgguimenucolumns_74',['KGGuiMenuColumns',['../structKGGuiMenuColumns.html',1,'']]],
  ['kgguimetricsconfig_75',['KGGuiMetricsConfig',['../structKGGuiMetricsConfig.html',1,'']]],
  ['kgguinavitemdata_76',['KGGuiNavItemData',['../structKGGuiNavItemData.html',1,'']]],
  ['kgguinextitemdata_77',['KGGuiNextItemData',['../structKGGuiNextItemData.html',1,'']]],
  ['kgguinextwindowdata_78',['KGGuiNextWindowData',['../structKGGuiNextWindowData.html',1,'']]],
  ['kgguioldcolumndata_79',['KGGuiOldColumnData',['../structKGGuiOldColumnData.html',1,'']]],
  ['kgguioldcolumns_80',['KGGuiOldColumns',['../structKGGuiOldColumns.html',1,'']]],
  ['kgguipopupdata_81',['KGGuiPopupData',['../structKGGuiPopupData.html',1,'']]],
  ['kgguiptrorindex_82',['KGGuiPtrOrIndex',['../structKGGuiPtrOrIndex.html',1,'']]],
  ['kgguisettingshandler_83',['KGGuiSettingsHandler',['../structKGGuiSettingsHandler.html',1,'']]],
  ['kgguishrinkwidthitem_84',['KGGuiShrinkWidthItem',['../structKGGuiShrinkWidthItem.html',1,'']]],
  ['kgguistacklevelinfo_85',['KGGuiStackLevelInfo',['../structKGGuiStackLevelInfo.html',1,'']]],
  ['kgguistacksizes_86',['KGGuiStackSizes',['../structKGGuiStackSizes.html',1,'']]],
  ['kgguistacktool_87',['KGGuiStackTool',['../structKGGuiStackTool.html',1,'']]],
  ['kgguistylemod_88',['KGGuiStyleMod',['../structKGGuiStyleMod.html',1,'']]],
  ['kgguitabbar_89',['KGGuiTabBar',['../structKGGuiTabBar.html',1,'']]],
  ['kgguitabitem_90',['KGGuiTabItem',['../structKGGuiTabItem.html',1,'']]],
  ['kgguitable_91',['KGGuiTable',['../structKGGuiTable.html',1,'']]],
  ['kgguitablecelldata_92',['KGGuiTableCellData',['../structKGGuiTableCellData.html',1,'']]],
  ['kgguitablecolumn_93',['KGGuiTableColumn',['../structKGGuiTableColumn.html',1,'']]],
  ['kgguitablecolumnsettings_94',['KGGuiTableColumnSettings',['../structKGGuiTableColumnSettings.html',1,'']]],
  ['kgguitableinstancedata_95',['KGGuiTableInstanceData',['../structKGGuiTableInstanceData.html',1,'']]],
  ['kgguitablesettings_96',['KGGuiTableSettings',['../structKGGuiTableSettings.html',1,'']]],
  ['kgguitabletempdata_97',['KGGuiTableTempData',['../structKGGuiTableTempData.html',1,'']]],
  ['kgguitextindex_98',['KGGuiTextIndex',['../structKGGuiTextIndex.html',1,'']]],
  ['kgguiviewportp_99',['KGGuiViewportP',['../structKGGuiViewportP.html',1,'']]],
  ['kgguiwindow_100',['KGGuiWindow',['../structKGGuiWindow.html',1,'']]],
  ['kgguiwindowsettings_101',['KGGuiWindowSettings',['../structKGGuiWindowSettings.html',1,'']]],
  ['kgguiwindowstackdata_102',['KGGuiWindowStackData',['../structKGGuiWindowStackData.html',1,'']]],
  ['kgguiwindowtempdata_103',['KGGuiWindowTempData',['../structKGGuiWindowTempData.html',1,'']]],
  ['kgpool_104',['KGPool',['../structKGPool.html',1,'']]],
  ['kgpool_3c_20kgguitabbar_20_3e_105',['KGPool&lt; KGGuiTabBar &gt;',['../structKGPool.html',1,'']]],
  ['kgpool_3c_20kgguitable_20_3e_106',['KGPool&lt; KGGuiTable &gt;',['../structKGPool.html',1,'']]],
  ['kgrect_107',['KGRect',['../structKGRect.html',1,'']]],
  ['kgspan_108',['KGSpan',['../structKGSpan.html',1,'']]],
  ['kgspan_3c_20kgguitablecelldata_20_3e_109',['KGSpan&lt; KGGuiTableCellData &gt;',['../structKGSpan.html',1,'']]],
  ['kgspan_3c_20kgguitablecolumn_20_3e_110',['KGSpan&lt; KGGuiTableColumn &gt;',['../structKGSpan.html',1,'']]],
  ['kgspan_3c_20kgguitablecolumnidx_20_3e_111',['KGSpan&lt; KGGuiTableColumnIdx &gt;',['../structKGSpan.html',1,'']]],
  ['kgspanallocator_112',['KGSpanAllocator',['../structKGSpanAllocator.html',1,'']]],
  ['kgvec1_113',['KGVec1',['../structKGVec1.html',1,'']]],
  ['kgvec2_114',['KGVec2',['../structKGVec2.html',1,'']]],
  ['kgvec2ih_115',['KGVec2ih',['../structKGVec2ih.html',1,'']]],
  ['kgvec4_116',['KGVec4',['../structKGVec4.html',1,'']]],
  ['kgvector_117',['KGVector',['../structKGVector.html',1,'']]],
  ['kgvector_3c_20char_20_3e_118',['KGVector&lt; char &gt;',['../structKGVector.html',1,'']]],
  ['kgvector_3c_20float_20_3e_119',['KGVector&lt; float &gt;',['../structKGVector.html',1,'']]],
  ['kgvector_3c_20int_20_3e_120',['KGVector&lt; int &gt;',['../structKGVector.html',1,'']]],
  ['kgvector_3c_20karmaguiplatformmonitor_20_3e_121',['KGVector&lt; KarmaGuiPlatformMonitor &gt;',['../structKGVector.html',1,'']]],
  ['kgvector_3c_20karmaguistorage_3a_3aimguistoragepair_20_3e_122',['KGVector&lt; KarmaGuiStorage::ImGuiStoragePair &gt;',['../structKGVector.html',1,'']]],
  ['kgvector_3c_20karmaguitablecolumnsortspecs_20_3e_123',['KGVector&lt; KarmaGuiTableColumnSortSpecs &gt;',['../structKGVector.html',1,'']]],
  ['kgvector_3c_20karmaguitextfilter_3a_3aimguitextrange_20_3e_124',['KGVector&lt; KarmaGuiTextFilter::ImGuiTextRange &gt;',['../structKGVector.html',1,'']]],
  ['kgvector_3c_20karmaguiviewport_20_2a_20_3e_125',['KGVector&lt; KarmaGuiViewport * &gt;',['../structKGVector.html',1,'']]],
  ['kgvector_3c_20kgdrawchannel_20_3e_126',['KGVector&lt; KGDrawChannel &gt;',['../structKGVector.html',1,'']]],
  ['kgvector_3c_20kgdrawcmd_20_3e_127',['KGVector&lt; KGDrawCmd &gt;',['../structKGVector.html',1,'']]],
  ['kgvector_3c_20kgdrawidx_20_3e_128',['KGVector&lt; KGDrawIdx &gt;',['../structKGVector.html',1,'']]],
  ['kgvector_3c_20kgdrawlist_20_2a_20_3e_129',['KGVector&lt; KGDrawList * &gt;',['../structKGVector.html',1,'']]],
  ['kgvector_3c_20kgdrawvert_20_3e_130',['KGVector&lt; KGDrawVert &gt;',['../structKGVector.html',1,'']]],
  ['kgvector_3c_20kgfont_20_2a_20_3e_131',['KGVector&lt; KGFont * &gt;',['../structKGVector.html',1,'']]],
  ['kgvector_3c_20kgfontatlascustomrect_20_3e_132',['KGVector&lt; KGFontAtlasCustomRect &gt;',['../structKGVector.html',1,'']]],
  ['kgvector_3c_20kgfontconfig_20_3e_133',['KGVector&lt; KGFontConfig &gt;',['../structKGVector.html',1,'']]],
  ['kgvector_3c_20kgfontglyph_20_3e_134',['KGVector&lt; KGFontGlyph &gt;',['../structKGVector.html',1,'']]],
  ['kgvector_3c_20kgguicolormod_20_3e_135',['KGVector&lt; KGGuiColorMod &gt;',['../structKGVector.html',1,'']]],
  ['kgvector_3c_20kgguicontexthook_20_3e_136',['KGVector&lt; KGGuiContextHook &gt;',['../structKGVector.html',1,'']]],
  ['kgvector_3c_20kgguigroupdata_20_3e_137',['KGVector&lt; KGGuiGroupData &gt;',['../structKGVector.html',1,'']]],
  ['kgvector_3c_20kgguiid_20_3e_138',['KGVector&lt; KGGuiID &gt;',['../structKGVector.html',1,'']]],
  ['kgvector_3c_20kgguiinputevent_20_3e_139',['KGVector&lt; KGGuiInputEvent &gt;',['../structKGVector.html',1,'']]],
  ['kgvector_3c_20kgguiitemflags_20_3e_140',['KGVector&lt; KGGuiItemFlags &gt;',['../structKGVector.html',1,'']]],
  ['kgvector_3c_20kgguikeyroutingdata_20_3e_141',['KGVector&lt; KGGuiKeyRoutingData &gt;',['../structKGVector.html',1,'']]],
  ['kgvector_3c_20kgguilistclipperdata_20_3e_142',['KGVector&lt; KGGuiListClipperData &gt;',['../structKGVector.html',1,'']]],
  ['kgvector_3c_20kgguilistclipperrange_20_3e_143',['KGVector&lt; KGGuiListClipperRange &gt;',['../structKGVector.html',1,'']]],
  ['kgvector_3c_20kgguioldcolumndata_20_3e_144',['KGVector&lt; KGGuiOldColumnData &gt;',['../structKGVector.html',1,'']]],
  ['kgvector_3c_20kgguioldcolumns_20_3e_145',['KGVector&lt; KGGuiOldColumns &gt;',['../structKGVector.html',1,'']]],
  ['kgvector_3c_20kgguipopupdata_20_3e_146',['KGVector&lt; KGGuiPopupData &gt;',['../structKGVector.html',1,'']]],
  ['kgvector_3c_20kgguiptrorindex_20_3e_147',['KGVector&lt; KGGuiPtrOrIndex &gt;',['../structKGVector.html',1,'']]],
  ['kgvector_3c_20kgguisettingshandler_20_3e_148',['KGVector&lt; KGGuiSettingsHandler &gt;',['../structKGVector.html',1,'']]],
  ['kgvector_3c_20kgguishrinkwidthitem_20_3e_149',['KGVector&lt; KGGuiShrinkWidthItem &gt;',['../structKGVector.html',1,'']]],
  ['kgvector_3c_20kgguistacklevelinfo_20_3e_150',['KGVector&lt; KGGuiStackLevelInfo &gt;',['../structKGVector.html',1,'']]],
  ['kgvector_3c_20kgguistylemod_20_3e_151',['KGVector&lt; KGGuiStyleMod &gt;',['../structKGVector.html',1,'']]],
  ['kgvector_3c_20kgguitabbar_20_3e_152',['KGVector&lt; KGGuiTabBar &gt;',['../structKGVector.html',1,'']]],
  ['kgvector_3c_20kgguitabitem_20_3e_153',['KGVector&lt; KGGuiTabItem &gt;',['../structKGVector.html',1,'']]],
  ['kgvector_3c_20kgguitable_20_3e_154',['KGVector&lt; KGGuiTable &gt;',['../structKGVector.html',1,'']]],
  ['kgvector_3c_20kgguitableinstancedata_20_3e_155',['KGVector&lt; KGGuiTableInstanceData &gt;',['../structKGVector.html',1,'']]],
  ['kgvector_3c_20kgguitabletempdata_20_3e_156',['KGVector&lt; KGGuiTableTempData &gt;',['../structKGVector.html',1,'']]],
  ['kgvector_3c_20kgguiviewportp_20_2a_20_3e_157',['KGVector&lt; KGGuiViewportP * &gt;',['../structKGVector.html',1,'']]],
  ['kgvector_3c_20kgguiwindow_20_2a_20_3e_158',['KGVector&lt; KGGuiWindow * &gt;',['../structKGVector.html',1,'']]],
  ['kgvector_3c_20kgguiwindowstackdata_20_3e_159',['KGVector&lt; KGGuiWindowStackData &gt;',['../structKGVector.html',1,'']]],
  ['kgvector_3c_20kgtextureid_20_3e_160',['KGVector&lt; KGTextureID &gt;',['../structKGVector.html',1,'']]],
  ['kgvector_3c_20kgu32_20_3e_161',['KGVector&lt; KGU32 &gt;',['../structKGVector.html',1,'']]],
  ['kgvector_3c_20kgvec2_20_3e_162',['KGVector&lt; KGVec2 &gt;',['../structKGVector.html',1,'']]],
  ['kgvector_3c_20kgvec4_20_3e_163',['KGVector&lt; KGVec4 &gt;',['../structKGVector.html',1,'']]],
  ['kgvector_3c_20kgwchar_20_3e_164',['KGVector&lt; KGWchar &gt;',['../structKGVector.html',1,'']]],
  ['kgvector_3c_20unsigned_20char_20_3e_165',['KGVector&lt; unsigned char &gt;',['../structKGVector.html',1,'']]]
];
